<?xml version="1.0" encoding="utf-8"?><Database Name="Formularium2010" Class="CompleteDatabaseDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=HAL-2008;Initial Catalog=Formularium2010;Integrated Security=True" SettingsObjectName="Informedica.GenForm.Database.Properties.Settings" SettingsPropertyName="Formularium2010ConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.Verpakking" Member="Verpakking">
    <Type Name="Verpakking">
      <Column Name="verpakkingId" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="naam" Type="System.String" DbType="NChar(125) NOT NULL" CanBeNull="false" />
      <Column Name="versieTimeStamp" Type="System.Data.Linq.Binary" DbType="rowversion NOT NULL" CanBeNull="false" IsVersion="true" />
      <Association Name="Verpakking_ToedienVormVerpakking" Member="ToedienVormVerpakking" ThisKey="verpakkingId" OtherKey="verpakkingId" Type="ToedienVormVerpakking" />
      <Association Name="Verpakking_Artikel" Member="Artikel" ThisKey="verpakkingId" OtherKey="verpakkingId" Type="Artikel" />
    </Type>
  </Table>
  <Table Name="dbo.ToepassingGroep" Member="ToepassingGroep">
    <Type Name="ToepassingGroep">
      <Column Name="toepassingGroepId" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="naam" Type="System.String" DbType="NChar(125) NOT NULL" CanBeNull="false" />
      <Column Name="versieTimeStamp" Type="System.Data.Linq.Binary" DbType="rowversion NOT NULL" CanBeNull="false" IsVersion="true" />
      <Column Name="formulariumId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="hoofdGroep" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="ToepassingGroep_ToepassingGroep" Member="ToepassingGroep2" ThisKey="toepassingGroepId" OtherKey="hoofdGroep" Type="ToepassingGroep" />
      <Association Name="ToepassingGroep_ToepassingBijzonderheid" Member="ToepassingBijzonderheid" ThisKey="toepassingGroepId" OtherKey="toepassingGroepId" Type="ToepassingBijzonderheid" />
      <Association Name="ToepassingGroep_PublicatieTherapieGroep" Member="PublicatieTherapieGroep" ThisKey="toepassingGroepId" OtherKey="therapieGroep" Type="PublicatieTherapieGroep" />
      <Association Name="ToepassingGroep_PublicatieHoofdstuk" Member="PublicatieHoofdstuk" ThisKey="toepassingGroepId" OtherKey="hoofdstuk" Type="PublicatieHoofdstuk" />
      <Association Name="ToepassingGroep_DoseringToepassing" Member="DoseringToepassing" ThisKey="toepassingGroepId" OtherKey="toepassingGroepId" Type="DoseringToepassing" />
      <Association Name="ToepassingGroep_ToepassingGroep" Member="ToepassingGroep1" ThisKey="hoofdGroep" OtherKey="toepassingGroepId" Type="ToepassingGroep" IsForeignKey="true" />
      <Association Name="Formularium_ToepassingGroep" Member="Formularium" ThisKey="formulariumId" OtherKey="formulariumId" Type="Formularium" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.ToepassingBijzonderheid" Member="ToepassingBijzonderheid">
    <Type Name="ToepassingBijzonderheid">
      <Column Name="toepassingBijzonderheidId" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="toepassingGroepId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="formulariumId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="tekstItemId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="ToepassingGroep_ToepassingBijzonderheid" Member="ToepassingGroep" ThisKey="toepassingGroepId" OtherKey="toepassingGroepId" Type="ToepassingGroep" IsForeignKey="true" />
      <Association Name="TekstItem_ToepassingBijzonderheid" Member="TekstItem" ThisKey="tekstItemId" OtherKey="tekstItemId" Type="TekstItem" IsForeignKey="true" />
      <Association Name="Formularium_ToepassingBijzonderheid" Member="Formularium" ThisKey="formulariumId" OtherKey="formulariumId" Type="Formularium" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.ToedienVormVerpakking" Member="ToedienVormVerpakking">
    <Type Name="ToedienVormVerpakking">
      <Column Name="toedienVormVerpakkingId" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="toedienVormId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="verpakkingId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="Verpakking_ToedienVormVerpakking" Member="Verpakking" ThisKey="verpakkingId" OtherKey="verpakkingId" Type="Verpakking" IsForeignKey="true" />
      <Association Name="ToedienVorm_ToedienVormVerpakking" Member="ToedienVorm" ThisKey="toedienVormId" OtherKey="toedienVormId" Type="ToedienVorm" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.ToedienVormRoute" Member="ToedienVormRoute">
    <Type Name="ToedienVormRoute">
      <Column Name="toedienVormRouteId" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="toedienVormId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="routeId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="ToedienVorm_ToedienVormRoute" Member="ToedienVorm" ThisKey="toedienVormId" OtherKey="toedienVormId" Type="ToedienVorm" IsForeignKey="true" />
      <Association Name="Route_ToedienVormRoute" Member="Route" ThisKey="routeId" OtherKey="routeId" Type="Route" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.ToedienVormEenheid" Member="ToedienVormEenheid">
    <Type Name="ToedienVormEenheid">
      <Column Name="toedienVormEenheidId" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="toedienVormId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="eenheidId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="ToedienVorm_ToedienVormEenheid" Member="ToedienVorm" ThisKey="toedienVormId" OtherKey="toedienVormId" Type="ToedienVorm" IsForeignKey="true" />
      <Association Name="Eenheid_ToedienVormEenheid" Member="Eenheid" ThisKey="eenheidId" OtherKey="eenheidId" Type="Eenheid" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.ToedienVorm" Member="ToedienVorm">
    <Type Name="ToedienVorm">
      <Column Name="toedienVormId" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="naam" Type="System.String" DbType="NChar(125) NOT NULL" CanBeNull="false" />
      <Column Name="versieTimeStamp" Type="System.Data.Linq.Binary" DbType="rowversion NOT NULL" CanBeNull="false" IsVersion="true" />
      <Association Name="ToedienVorm_ToedienVormVerpakking" Member="ToedienVormVerpakking" ThisKey="toedienVormId" OtherKey="toedienVormId" Type="ToedienVormVerpakking" />
      <Association Name="ToedienVorm_ToedienVormRoute" Member="ToedienVormRoute" ThisKey="toedienVormId" OtherKey="toedienVormId" Type="ToedienVormRoute" />
      <Association Name="ToedienVorm_ToedienVormEenheid" Member="ToedienVormEenheid" ThisKey="toedienVormId" OtherKey="toedienVormId" Type="ToedienVormEenheid" />
      <Association Name="ToedienVorm_Artikel" Member="Artikel" ThisKey="toedienVormId" OtherKey="toedienVormId" Type="Artikel" />
    </Type>
  </Table>
  <Table Name="dbo.TekstLog" Member="TekstLog">
    <Type Name="TekstLog">
      <Column Name="tekstLogId" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="logDatum" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="tekstItemId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="formulariumId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="gebruikerId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="actie" Type="System.String" DbType="NChar(50) NOT NULL" CanBeNull="false" />
      <Association Name="TekstItem_TekstLog" Member="TekstItem" ThisKey="tekstItemId" OtherKey="tekstItemId" Type="TekstItem" IsForeignKey="true" />
      <Association Name="Gebruiker_TekstLog" Member="Gebruiker" ThisKey="gebruikerId" OtherKey="gebruikerId" Type="Gebruiker" IsForeignKey="true" />
      <Association Name="Formularium_TekstLog" Member="Formularium" ThisKey="formulariumId" OtherKey="formulariumId" Type="Formularium" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.TekstItem" Member="TekstItem">
    <Type Name="TekstItem">
      <Column Name="tekstItemId" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="versieTimeStamp" Type="System.Data.Linq.Binary" DbType="rowversion NOT NULL" CanBeNull="false" IsVersion="true" />
      <Column Name="tekst" Type="System.String" DbType="NVarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="tekstType" Type="System.String" DbType="NChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="tekstStatus" Type="System.String" DbType="NChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="tekstKop" Type="System.String" DbType="NChar(125)" CanBeNull="true" />
      <Association Name="TekstItem_ToepassingBijzonderheid" Member="ToepassingBijzonderheid" ThisKey="tekstItemId" OtherKey="tekstItemId" Type="ToepassingBijzonderheid" />
      <Association Name="TekstItem_TekstLog" Member="TekstLog" ThisKey="tekstItemId" OtherKey="tekstItemId" Type="TekstLog" />
      <Association Name="TekstItem_PublicatieTherapieGroep" Member="PublicatieTherapieGroep" ThisKey="tekstItemId" OtherKey="inleiding" Type="PublicatieTherapieGroep" />
      <Association Name="TekstItem_PublicatieRoute" Member="PublicatieRoute" ThisKey="tekstItemId" OtherKey="routeDosering" Type="PublicatieRoute" />
      <Association Name="TekstItem_PublicatieRoute1" Member="PublicatieRoute1" ThisKey="tekstItemId" OtherKey="bijzonderheid" Type="PublicatieRoute" />
      <Association Name="TekstItem_PublicatieHoofdstuk" Member="PublicatieHoofdstuk" ThisKey="tekstItemId" OtherKey="inleiding" Type="PublicatieHoofdstuk" />
      <Association Name="TekstItem_PublicatieGeneriek" Member="PublicatieGeneriek" ThisKey="tekstItemId" OtherKey="generiekBijzonderheid" Type="PublicatieGeneriek" />
      <Association Name="TekstItem_PublicatieFormulariumTekst" Member="PublicatieFormulariumTekst" ThisKey="tekstItemId" OtherKey="formulariumTekst" Type="PublicatieFormulariumTekst" />
      <Association Name="TekstItem_PublicatieArtikel" Member="PublicatieArtikel" ThisKey="tekstItemId" OtherKey="artikelDosering" Type="PublicatieArtikel" />
      <Association Name="TekstItem_PublicatieArtikel1" Member="PublicatieArtikel1" ThisKey="tekstItemId" OtherKey="bijzonderheid" Type="PublicatieArtikel" />
      <Association Name="TekstItem_GeneriekDosering" Member="GeneriekDosering" ThisKey="tekstItemId" OtherKey="tekstItemId" Type="GeneriekDosering" />
      <Association Name="TekstItem_GeneriekBijzonderheid" Member="GeneriekBijzonderheid" ThisKey="tekstItemId" OtherKey="tekstItemId" Type="GeneriekBijzonderheid" />
      <Association Name="TekstItem_FormulariumTekst" Member="FormulariumTekst" ThisKey="tekstItemId" OtherKey="tekstItemId" Type="FormulariumTekst" />
      <Association Name="TekstItem_ArtikelBijzonderheid" Member="ArtikelBijzonderheid" ThisKey="tekstItemId" OtherKey="tekstItemId" Type="ArtikelBijzonderheid" />
    </Type>
  </Table>
  <Table Name="dbo.Route" Member="Route">
    <Type Name="Route">
      <Column Name="routeId" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="naam" Type="System.String" DbType="NChar(125) NOT NULL" CanBeNull="false" />
      <Column Name="versieTimeStamp" Type="System.Data.Linq.Binary" DbType="rowversion NOT NULL" CanBeNull="false" IsVersion="true" />
      <Association Name="Route_ToedienVormRoute" Member="ToedienVormRoute" ThisKey="routeId" OtherKey="routeId" Type="ToedienVormRoute" />
      <Association Name="Route_PublicatieRoute" Member="PublicatieRoute" ThisKey="routeId" OtherKey="routeId" Type="PublicatieRoute" />
      <Association Name="Route_DoseringRoute" Member="DoseringRoute" ThisKey="routeId" OtherKey="routeId" Type="DoseringRoute" />
      <Association Name="Route_ArtikelRoute" Member="ArtikelRoute" ThisKey="routeId" OtherKey="routeId" Type="ArtikelRoute" />
    </Type>
  </Table>
  <Table Name="dbo.Rol" Member="Rol">
    <Type Name="Rol">
      <Column Name="rolId" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="naam" Type="System.String" DbType="NChar(30) NOT NULL" CanBeNull="false" />
      <Column Name="versieTimeStamp" Type="System.Data.Linq.Binary" DbType="rowversion NOT NULL" CanBeNull="false" IsVersion="true" />
      <Column Name="omschrijving" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Association Name="Rol_GebruikerRol" Member="GebruikerRol" ThisKey="rolId" OtherKey="rolId" Type="GebruikerRol" />
    </Type>
  </Table>
  <Table Name="dbo.PublicatieTherapieGroep" Member="PublicatieTherapieGroep">
    <Type Name="PublicatieTherapieGroep">
      <Column Name="publicatieTherapieGroepId" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="publicatieHoofdstukId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="therapieGroep" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="inleiding" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="PublicatieTherapieGroep_PublicatieGeneriek" Member="PublicatieGeneriek" ThisKey="publicatieTherapieGroepId" OtherKey="publicatieTherapieGroepId" Type="PublicatieGeneriek" />
      <Association Name="ToepassingGroep_PublicatieTherapieGroep" Member="ToepassingGroep" ThisKey="therapieGroep" OtherKey="toepassingGroepId" Type="ToepassingGroep" IsForeignKey="true" />
      <Association Name="TekstItem_PublicatieTherapieGroep" Member="TekstItem" ThisKey="inleiding" OtherKey="tekstItemId" Type="TekstItem" IsForeignKey="true" />
      <Association Name="PublicatieHoofdstuk_PublicatieTherapieGroep" Member="PublicatieHoofdstuk" ThisKey="publicatieHoofdstukId" OtherKey="publicatieHoofdstukId" Type="PublicatieHoofdstuk" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.PublicatieRoute" Member="PublicatieRoute">
    <Type Name="PublicatieRoute">
      <Column Name="publicatieRouteId" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="publicatieGeneriekId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="routeId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="routeDosering" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="bijzonderheid" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="PublicatieRoute_PublicatieArtikel" Member="PublicatieArtikel" ThisKey="publicatieRouteId" OtherKey="publicatieRouteId" Type="PublicatieArtikel" />
      <Association Name="Route_PublicatieRoute" Member="Route" ThisKey="routeId" OtherKey="routeId" Type="Route" IsForeignKey="true" />
      <Association Name="TekstItem_PublicatieRoute" Member="TekstItem" ThisKey="routeDosering" OtherKey="tekstItemId" Type="TekstItem" IsForeignKey="true" />
      <Association Name="TekstItem_PublicatieRoute1" Member="TekstItem1" ThisKey="bijzonderheid" OtherKey="tekstItemId" Type="TekstItem" IsForeignKey="true" />
      <Association Name="PublicatieGeneriek_PublicatieRoute" Member="PublicatieGeneriek" ThisKey="publicatieGeneriekId" OtherKey="publicatieGeneriekId" Type="PublicatieGeneriek" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.PublicatieHoofdstuk" Member="PublicatieHoofdstuk">
    <Type Name="PublicatieHoofdstuk">
      <Column Name="publicatieHoofdstukId" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="publicatieId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="hoofdstuk" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="inleiding" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="PublicatieHoofdstuk_PublicatieTherapieGroep" Member="PublicatieTherapieGroep" ThisKey="publicatieHoofdstukId" OtherKey="publicatieHoofdstukId" Type="PublicatieTherapieGroep" />
      <Association Name="ToepassingGroep_PublicatieHoofdstuk" Member="ToepassingGroep" ThisKey="hoofdstuk" OtherKey="toepassingGroepId" Type="ToepassingGroep" IsForeignKey="true" />
      <Association Name="TekstItem_PublicatieHoofdstuk" Member="TekstItem" ThisKey="inleiding" OtherKey="tekstItemId" Type="TekstItem" IsForeignKey="true" />
      <Association Name="Publicatie_PublicatieHoofdstuk" Member="Publicatie" ThisKey="publicatieId" OtherKey="publicatieId" Type="Publicatie" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.PublicatieGeneriek" Member="PublicatieGeneriek">
    <Type Name="PublicatieGeneriek">
      <Column Name="publicatieGeneriekId" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="publicatieTherapieGroepId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="generiekId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="generiekBijzonderheid" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="PublicatieGeneriek_PublicatieRoute" Member="PublicatieRoute" ThisKey="publicatieGeneriekId" OtherKey="publicatieGeneriekId" Type="PublicatieRoute" />
      <Association Name="PublicatieTherapieGroep_PublicatieGeneriek" Member="PublicatieTherapieGroep" ThisKey="publicatieTherapieGroepId" OtherKey="publicatieTherapieGroepId" Type="PublicatieTherapieGroep" IsForeignKey="true" />
      <Association Name="TekstItem_PublicatieGeneriek" Member="TekstItem" ThisKey="generiekBijzonderheid" OtherKey="tekstItemId" Type="TekstItem" IsForeignKey="true" />
      <Association Name="Generiek_PublicatieGeneriek" Member="Generiek" ThisKey="generiekId" OtherKey="generiekId" Type="Generiek" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.PublicatieFormulariumTekst" Member="PublicatieFormulariumTekst">
    <Type Name="PublicatieFormulariumTekst">
      <Column Name="publicatieFormulariumTekstId" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="publicatieId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="formulariumTekst" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="TekstItem_PublicatieFormulariumTekst" Member="TekstItem" ThisKey="formulariumTekst" OtherKey="tekstItemId" Type="TekstItem" IsForeignKey="true" />
      <Association Name="Publicatie_PublicatieFormulariumTekst" Member="Publicatie" ThisKey="publicatieId" OtherKey="publicatieId" Type="Publicatie" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.PublicatieArtikel" Member="PublicatieArtikel">
    <Type Name="PublicatieArtikel">
      <Column Name="publicatieArtikelId" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="publicatieRouteId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="artikelId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="artikelDosering" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="bijzonderheid" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="PublicatieRoute_PublicatieArtikel" Member="PublicatieRoute" ThisKey="publicatieRouteId" OtherKey="publicatieRouteId" Type="PublicatieRoute" IsForeignKey="true" />
      <Association Name="TekstItem_PublicatieArtikel" Member="TekstItem" ThisKey="artikelDosering" OtherKey="tekstItemId" Type="TekstItem" IsForeignKey="true" />
      <Association Name="TekstItem_PublicatieArtikel1" Member="TekstItem1" ThisKey="bijzonderheid" OtherKey="tekstItemId" Type="TekstItem" IsForeignKey="true" />
      <Association Name="Artikel_PublicatieArtikel" Member="Artikel" ThisKey="artikelId" OtherKey="artikelId" Type="Artikel" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Publicatie" Member="Publicatie">
    <Type Name="Publicatie">
      <Column Name="publicatieId" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="publicatieDatum" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="formulariumId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="gebruikerId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="Publicatie_PublicatieHoofdstuk" Member="PublicatieHoofdstuk" ThisKey="publicatieId" OtherKey="publicatieId" Type="PublicatieHoofdstuk" />
      <Association Name="Publicatie_PublicatieFormulariumTekst" Member="PublicatieFormulariumTekst" ThisKey="publicatieId" OtherKey="publicatieId" Type="PublicatieFormulariumTekst" />
      <Association Name="Gebruiker_Publicatie" Member="Gebruiker" ThisKey="gebruikerId" OtherKey="gebruikerId" Type="Gebruiker" IsForeignKey="true" />
      <Association Name="Formularium_Publicatie" Member="Formularium" ThisKey="formulariumId" OtherKey="formulariumId" Type="Formularium" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Merk" Member="Merk">
    <Type Name="Merk">
      <Column Name="merkId" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="naam" Type="System.String" DbType="NChar(125) NOT NULL" CanBeNull="false" />
      <Column Name="versieTimeStamp" Type="System.Data.Linq.Binary" DbType="rowversion NOT NULL" CanBeNull="false" IsVersion="true" />
      <Association Name="Merk_Artikel" Member="Artikel" ThisKey="merkId" OtherKey="merkId" Type="Artikel" />
    </Type>
  </Table>
  <Table Name="dbo.GeneriekGroep" Member="GeneriekGroep">
    <Type Name="GeneriekGroep">
      <Column Name="generiekGroepId" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="naam" Type="System.String" DbType="NChar(125) NOT NULL" CanBeNull="false" />
      <Column Name="versieTimeStamp" Type="System.Data.Linq.Binary" DbType="rowversion NOT NULL" CanBeNull="false" IsVersion="true" />
      <Column Name="hoofdGroep" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="GeneriekGroep_GeneriekGroep" Member="GeneriekGroep2" ThisKey="generiekGroepId" OtherKey="hoofdGroep" Type="GeneriekGroep" />
      <Association Name="GeneriekGroep_Generiek" Member="Generiek" ThisKey="generiekGroepId" OtherKey="generiekGroepId" Type="Generiek" />
      <Association Name="GeneriekGroep_GeneriekGroep" Member="GeneriekGroep1" ThisKey="hoofdGroep" OtherKey="generiekGroepId" Type="GeneriekGroep" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.GeneriekDosering" Member="GeneriekDosering">
    <Type Name="GeneriekDosering">
      <Column Name="generiekDoseringId" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="versieTimeStamp" Type="System.Data.Linq.Binary" DbType="rowversion NOT NULL" CanBeNull="false" IsVersion="true" />
      <Column Name="tekstItemId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="generiekId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="formulariumId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="GeneriekDosering_DoseringToepassing" Member="DoseringToepassing" ThisKey="generiekDoseringId" OtherKey="generiekDoseringId" Type="DoseringToepassing" />
      <Association Name="GeneriekDosering_DoseringRoute" Member="DoseringRoute" ThisKey="generiekDoseringId" OtherKey="generiekDoseringId" Type="DoseringRoute" />
      <Association Name="GeneriekDosering_DoseringArtikel" Member="DoseringArtikel" ThisKey="generiekDoseringId" OtherKey="generiekDoseringId" Type="DoseringArtikel" />
      <Association Name="TekstItem_GeneriekDosering" Member="TekstItem" ThisKey="tekstItemId" OtherKey="tekstItemId" Type="TekstItem" IsForeignKey="true" />
      <Association Name="Generiek_GeneriekDosering" Member="Generiek" ThisKey="generiekId" OtherKey="generiekId" Type="Generiek" IsForeignKey="true" />
      <Association Name="Formularium_GeneriekDosering" Member="Formularium" ThisKey="formulariumId" OtherKey="formulariumId" Type="Formularium" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.GeneriekBijzonderheid" Member="GeneriekBijzonderheid">
    <Type Name="GeneriekBijzonderheid">
      <Column Name="generiekBijzonderheidId" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="generiekId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="formulariumId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="tekstItemId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="TekstItem_GeneriekBijzonderheid" Member="TekstItem" ThisKey="tekstItemId" OtherKey="tekstItemId" Type="TekstItem" IsForeignKey="true" />
      <Association Name="Generiek_GeneriekBijzonderheid" Member="Generiek" ThisKey="generiekId" OtherKey="generiekId" Type="Generiek" IsForeignKey="true" />
      <Association Name="Formularium_GeneriekBijzonderheid" Member="Formularium" ThisKey="formulariumId" OtherKey="formulariumId" Type="Formularium" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Generiek" Member="Generiek">
    <Type Name="Generiek">
      <Column Name="generiekId" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="naam" Type="System.String" DbType="NChar(125) NOT NULL" CanBeNull="false" />
      <Column Name="versieTimeStamp" Type="System.Data.Linq.Binary" DbType="rowversion NOT NULL" CanBeNull="false" IsVersion="true" />
      <Column Name="code" Type="System.String" DbType="NChar(125)" CanBeNull="true" />
      <Column Name="isStof" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="generiekGroepId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="Generiek_PublicatieGeneriek" Member="PublicatieGeneriek" ThisKey="generiekId" OtherKey="generiekId" Type="PublicatieGeneriek" />
      <Association Name="Generiek_GeneriekDosering" Member="GeneriekDosering" ThisKey="generiekId" OtherKey="generiekId" Type="GeneriekDosering" />
      <Association Name="Generiek_GeneriekBijzonderheid" Member="GeneriekBijzonderheid" ThisKey="generiekId" OtherKey="generiekId" Type="GeneriekBijzonderheid" />
      <Association Name="Generiek_ArtikelGeneriek" Member="ArtikelGeneriek" ThisKey="generiekId" OtherKey="generiekId" Type="ArtikelGeneriek" />
      <Association Name="Generiek_Artikel" Member="Artikel" ThisKey="generiekId" OtherKey="generiekId" Type="Artikel" />
      <Association Name="GeneriekGroep_Generiek" Member="GeneriekGroep" ThisKey="generiekGroepId" OtherKey="generiekGroepId" Type="GeneriekGroep" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.GebruikerRol" Member="GebruikerRol">
    <Type Name="GebruikerRol">
      <Column Name="gebruikerRolId" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="gebruikerId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="rolId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="Rol_GebruikerRol" Member="Rol" ThisKey="rolId" OtherKey="rolId" Type="Rol" IsForeignKey="true" />
      <Association Name="Gebruiker_GebruikerRol" Member="Gebruiker" ThisKey="gebruikerId" OtherKey="gebruikerId" Type="Gebruiker" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Gebruiker" Member="Gebruiker">
    <Type Name="Gebruiker">
      <Column Name="gebruikerId" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="gebruikerNaam" Type="System.String" DbType="NChar(30) NOT NULL" CanBeNull="false" />
      <Column Name="paswoord" Type="System.String" DbType="NChar(10) NOT NULL" CanBeNull="false" />
      <Column Name="email" Type="System.String" DbType="NChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="versieTimeStamp" Type="System.Data.Linq.Binary" DbType="rowversion NOT NULL" CanBeNull="false" IsVersion="true" />
      <Column Name="voorNaam" Type="System.String" DbType="NVarChar(125)" CanBeNull="true" />
      <Column Name="achterNaam" Type="System.String" DbType="NChar(125)" CanBeNull="true" />
      <Column Name="sein" Type="System.String" DbType="NChar(20)" CanBeNull="true" />
      <Association Name="Gebruiker_TekstLog" Member="TekstLog" ThisKey="gebruikerId" OtherKey="gebruikerId" Type="TekstLog" />
      <Association Name="Gebruiker_Publicatie" Member="Publicatie" ThisKey="gebruikerId" OtherKey="gebruikerId" Type="Publicatie" />
      <Association Name="Gebruiker_GebruikerRol" Member="GebruikerRol" ThisKey="gebruikerId" OtherKey="gebruikerId" Type="GebruikerRol" />
      <Association Name="Gebruiker_Apotheker" Member="Apotheker" ThisKey="gebruikerId" OtherKey="gebruikerId" Type="Apotheker" />
    </Type>
  </Table>
  <Table Name="dbo.FormulariumTekst" Member="FormulariumTekst">
    <Type Name="FormulariumTekst">
      <Column Name="formulariumTekstId" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="formulariumId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="tekstItemId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="TekstItem_FormulariumTekst" Member="TekstItem" ThisKey="tekstItemId" OtherKey="tekstItemId" Type="TekstItem" IsForeignKey="true" />
      <Association Name="Formularium_FormulariumTekst" Member="Formularium" ThisKey="formulariumId" OtherKey="formulariumId" Type="Formularium" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.FormulariumAuteur" Member="FormulariumAuteur">
    <Type Name="FormulariumAuteur">
      <Column Name="formulariumAuteurId" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="auteur" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="formulariumId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="Formularium_FormulariumAuteur" Member="Formularium" ThisKey="formulariumId" OtherKey="formulariumId" Type="Formularium" IsForeignKey="true" />
      <Association Name="Apotheker_FormulariumAuteur" Member="Apotheker" ThisKey="auteur" OtherKey="apothekerId" Type="Apotheker" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Formularium" Member="Formularium">
    <Type Name="Formularium">
      <Column Name="formulariumId" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="naam" Type="System.String" DbType="NVarChar(125) NOT NULL" CanBeNull="false" />
      <Column Name="versieTimeStamp" Type="System.Data.Linq.Binary" DbType="rowversion NOT NULL" CanBeNull="false" IsVersion="true" />
      <Column Name="apotheekId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="hoofdauteur" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="Formularium_ToepassingGroep" Member="ToepassingGroep" ThisKey="formulariumId" OtherKey="formulariumId" Type="ToepassingGroep" />
      <Association Name="Formularium_ToepassingBijzonderheid" Member="ToepassingBijzonderheid" ThisKey="formulariumId" OtherKey="formulariumId" Type="ToepassingBijzonderheid" />
      <Association Name="Formularium_TekstLog" Member="TekstLog" ThisKey="formulariumId" OtherKey="formulariumId" Type="TekstLog" />
      <Association Name="Formularium_Publicatie" Member="Publicatie" ThisKey="formulariumId" OtherKey="formulariumId" Type="Publicatie" />
      <Association Name="Formularium_GeneriekDosering" Member="GeneriekDosering" ThisKey="formulariumId" OtherKey="formulariumId" Type="GeneriekDosering" />
      <Association Name="Formularium_GeneriekBijzonderheid" Member="GeneriekBijzonderheid" ThisKey="formulariumId" OtherKey="formulariumId" Type="GeneriekBijzonderheid" />
      <Association Name="Formularium_FormulariumTekst" Member="FormulariumTekst" ThisKey="formulariumId" OtherKey="formulariumId" Type="FormulariumTekst" />
      <Association Name="Formularium_FormulariumAuteur" Member="FormulariumAuteur" ThisKey="formulariumId" OtherKey="formulariumId" Type="FormulariumAuteur" />
      <Association Name="Formularium_ArtikelBijzonderheid" Member="ArtikelBijzonderheid" ThisKey="formulariumId" OtherKey="formulariumId" Type="ArtikelBijzonderheid" />
      <Association Name="Apotheker_Formularium" Member="Apotheker" ThisKey="hoofdauteur" OtherKey="apothekerId" Type="Apotheker" IsForeignKey="true" />
      <Association Name="Apotheek_Formularium" Member="Apotheek" ThisKey="apotheekId" OtherKey="apotheekId" Type="Apotheek" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.EenheidGroep" Member="EenheidGroep">
    <Type Name="EenheidGroep">
      <Column Name="eenheidGroepId" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="versieTimeStamp" Type="System.Data.Linq.Binary" DbType="rowversion NOT NULL" CanBeNull="false" IsVersion="true" />
      <Column Name="naam" Type="System.String" DbType="NChar(125) NOT NULL" CanBeNull="false" />
      <Column Name="conversieToestaan" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Association Name="EenheidGroep_Eenheid" Member="Eenheid" ThisKey="eenheidGroepId" OtherKey="eenheidGroepId" Type="Eenheid" />
    </Type>
  </Table>
  <Table Name="dbo.Eenheid" Member="Eenheid">
    <Type Name="Eenheid">
      <Column Name="eenheidId" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="naam" Type="System.String" DbType="NChar(125) NOT NULL" CanBeNull="false" />
      <Column Name="versieTimeStamp" Type="System.Data.Linq.Binary" DbType="rowversion NOT NULL" CanBeNull="false" IsVersion="true" />
      <Column Name="eenheidGroepId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="afkorting" Type="System.String" DbType="NChar(125)" CanBeNull="true" />
      <Column Name="factor" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="KAE" Type="System.Single" DbType="Real" CanBeNull="true" />
      <Column Name="isReferentie" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Association Name="Eenheid_ToedienVormEenheid" Member="ToedienVormEenheid" ThisKey="eenheidId" OtherKey="eenheidId" Type="ToedienVormEenheid" />
      <Association Name="Eenheid_ArtikelGeneriek" Member="ArtikelGeneriek" ThisKey="eenheidId" OtherKey="eenheidId" Type="ArtikelGeneriek" />
      <Association Name="Eenheid_Artikel" Member="Artikel" ThisKey="eenheidId" OtherKey="eenheidId" Type="Artikel" />
      <Association Name="EenheidGroep_Eenheid" Member="EenheidGroep" ThisKey="eenheidGroepId" OtherKey="eenheidGroepId" Type="EenheidGroep" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.DoseringToepassing" Member="DoseringToepassing">
    <Type Name="DoseringToepassing">
      <Column Name="doseringToepassingId" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="generiekDoseringId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="toepassingGroepId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="GeneriekDosering_DoseringToepassing" Member="GeneriekDosering" ThisKey="generiekDoseringId" OtherKey="generiekDoseringId" Type="GeneriekDosering" IsForeignKey="true" />
      <Association Name="ToepassingGroep_DoseringToepassing" Member="ToepassingGroep" ThisKey="toepassingGroepId" OtherKey="toepassingGroepId" Type="ToepassingGroep" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.DoseringRoute" Member="DoseringRoute">
    <Type Name="DoseringRoute">
      <Column Name="doseringRouteId" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="generiekDoseringId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="routeId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="GeneriekDosering_DoseringRoute" Member="GeneriekDosering" ThisKey="generiekDoseringId" OtherKey="generiekDoseringId" Type="GeneriekDosering" IsForeignKey="true" />
      <Association Name="Route_DoseringRoute" Member="Route" ThisKey="routeId" OtherKey="routeId" Type="Route" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.DoseringArtikel" Member="DoseringArtikel">
    <Type Name="DoseringArtikel">
      <Column Name="doseringArtikelId" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="generiekDoseringId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="artikelId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="GeneriekDosering_DoseringArtikel" Member="GeneriekDosering" ThisKey="generiekDoseringId" OtherKey="generiekDoseringId" Type="GeneriekDosering" IsForeignKey="true" />
      <Association Name="Artikel_DoseringArtikel" Member="Artikel" ThisKey="artikelId" OtherKey="artikelId" Type="Artikel" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.ArtikelRoute" Member="ArtikelRoute">
    <Type Name="ArtikelRoute">
      <Column Name="artikelRouteId" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="artikelId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="routeId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="Route_ArtikelRoute" Member="Route" ThisKey="routeId" OtherKey="routeId" Type="Route" IsForeignKey="true" />
      <Association Name="Artikel_ArtikelRoute" Member="Artikel" ThisKey="artikelId" OtherKey="artikelId" Type="Artikel" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.ArtikelGeneriek" Member="ArtikelGeneriek">
    <Type Name="ArtikelGeneriek">
      <Column Name="artikelGeneriekId" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="volgorde" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="artikelId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="generiekId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="sterkte" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="hoeveelheid" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="eenheidId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="Generiek_ArtikelGeneriek" Member="Generiek" ThisKey="generiekId" OtherKey="generiekId" Type="Generiek" IsForeignKey="true" />
      <Association Name="Eenheid_ArtikelGeneriek" Member="Eenheid" ThisKey="eenheidId" OtherKey="eenheidId" Type="Eenheid" IsForeignKey="true" />
      <Association Name="Artikel_ArtikelGeneriek" Member="Artikel" ThisKey="artikelId" OtherKey="artikelId" Type="Artikel" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.ArtikelBijzonderheid" Member="ArtikelBijzonderheid">
    <Type Name="ArtikelBijzonderheid">
      <Column Name="artikelBijzonderheidId" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="artikelId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="formulariumId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="tekstItemId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="TekstItem_ArtikelBijzonderheid" Member="TekstItem" ThisKey="tekstItemId" OtherKey="tekstItemId" Type="TekstItem" IsForeignKey="true" />
      <Association Name="Formularium_ArtikelBijzonderheid" Member="Formularium" ThisKey="formulariumId" OtherKey="formulariumId" Type="Formularium" IsForeignKey="true" />
      <Association Name="Artikel_ArtikelBijzonderheid" Member="Artikel" ThisKey="artikelId" OtherKey="artikelId" Type="Artikel" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Artikel" Member="Artikel">
    <Type Name="Artikel">
      <Column Name="artikelId" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="naam" Type="System.String" DbType="NChar(125) NOT NULL" CanBeNull="false" />
      <Column Name="versieTimeStamp" Type="System.Data.Linq.Binary" DbType="rowversion NOT NULL" CanBeNull="false" IsVersion="true" />
      <Column Name="generiekId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="ArtikelGUID" Type="System.String" DbType="NChar(125)" CanBeNull="true" />
      <Column Name="HPKode" Type="System.String" DbType="NChar(125)" CanBeNull="true" />
      <Column Name="defaultNaam" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="KAE" Type="System.Single" DbType="Real" CanBeNull="true" />
      <Column Name="isCombinatie" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="ATKode" Type="System.String" DbType="NChar(125)" CanBeNull="true" />
      <Column Name="hoeveelheid" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="eenheidId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="toedienVormId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="verpakkingId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="merkId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="Artikel_PublicatieArtikel" Member="PublicatieArtikel" ThisKey="artikelId" OtherKey="artikelId" Type="PublicatieArtikel" />
      <Association Name="Artikel_DoseringArtikel" Member="DoseringArtikel" ThisKey="artikelId" OtherKey="artikelId" Type="DoseringArtikel" />
      <Association Name="Artikel_ArtikelRoute" Member="ArtikelRoute" ThisKey="artikelId" OtherKey="artikelId" Type="ArtikelRoute" />
      <Association Name="Artikel_ArtikelGeneriek" Member="ArtikelGeneriek" ThisKey="artikelId" OtherKey="artikelId" Type="ArtikelGeneriek" />
      <Association Name="Artikel_ArtikelBijzonderheid" Member="ArtikelBijzonderheid" ThisKey="artikelId" OtherKey="artikelId" Type="ArtikelBijzonderheid" />
      <Association Name="Generiek_Artikel" Member="Generiek" ThisKey="generiekId" OtherKey="generiekId" Type="Generiek" IsForeignKey="true" />
      <Association Name="Eenheid_Artikel" Member="Eenheid" ThisKey="eenheidId" OtherKey="eenheidId" Type="Eenheid" IsForeignKey="true" />
      <Association Name="ToedienVorm_Artikel" Member="ToedienVorm" ThisKey="toedienVormId" OtherKey="toedienVormId" Type="ToedienVorm" IsForeignKey="true" />
      <Association Name="Verpakking_Artikel" Member="Verpakking" ThisKey="verpakkingId" OtherKey="verpakkingId" Type="Verpakking" IsForeignKey="true" />
      <Association Name="Merk_Artikel" Member="Merk" ThisKey="merkId" OtherKey="merkId" Type="Merk" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Apotheker" Member="Apotheker">
    <Type Name="Apotheker">
      <Column Name="apothekerId" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="gebruikerId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="apotheekId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="Apotheker_FormulariumAuteur" Member="FormulariumAuteur" ThisKey="apothekerId" OtherKey="auteur" Type="FormulariumAuteur" />
      <Association Name="Apotheker_Formularium" Member="Formularium" ThisKey="apothekerId" OtherKey="hoofdauteur" Type="Formularium" />
      <Association Name="Gebruiker_Apotheker" Member="Gebruiker" ThisKey="gebruikerId" OtherKey="gebruikerId" Type="Gebruiker" IsForeignKey="true" />
      <Association Name="Apotheek_Apotheker" Member="Apotheek" ThisKey="apotheekId" OtherKey="apotheekId" Type="Apotheek" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Apotheek" Member="Apotheek">
    <Type Name="Apotheek">
      <Column Name="apotheekId" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="naam" Type="System.String" DbType="NVarChar(125) NOT NULL" CanBeNull="false" />
      <Column Name="versieTimeStamp" Type="System.Data.Linq.Binary" DbType="rowversion NOT NULL" CanBeNull="false" IsVersion="true" />
      <Association Name="Apotheek_Formularium" Member="Formularium" ThisKey="apotheekId" OtherKey="apotheekId" Type="Formularium" />
      <Association Name="Apotheek_Apotheker" Member="Apotheker" ThisKey="apotheekId" OtherKey="apotheekId" Type="Apotheker" />
    </Type>
  </Table>
</Database>