Ext.define('GenForm.test.TestList', {
    tests: [/*
        'GenForm.test.extjs.ClassTests',
        'GenForm.test.extjs.ComponentQueryTests',
        'GenForm.test.extjs.LoaderTests',
        'GenForm.test.extjs.ModelTests',
        'GenForm.test.extjs.StoreTests',
        'GenForm.test.util.FormCreatorTests',
        'GenForm.test.util.FormDataRetrieverTests',*/
        'GenForm.test.server.EnvironmentTests',/*
        'GenForm.test.server.ProductTests',*/
        'GenForm.test.controller.LoginControllerTests',/*
        'GenForm.test.controller.ProductControllerTests',
        'GenForm.test.controller.handler.ProductHandlerTests',
        'GenForm.test.model.BrandNameModelTests',
        'GenForm.test.model.ShapeModelTests',
        'GenForm.test.model.PackageModelTests',
        'GenForm.test.model.UnitModelTests',
        'GenForm.test.model.LoginModelTests',
        'GenForm.test.model.ProductModelTests',*/
        'GenForm.test.model.EnvironmentModelTests',/*
        'GenForm.test.model.ProductSubstanceModelTests',
        'GenForm.test.store.BrandNameStoreTests',
        'GenForm.test.store.ShapeNameStoreTests',
        'GenForm.test.store.PackageNameStoreTests',
        'GenForm.test.store.UnitNameStoreTests',
        'GenForm.test.store.SubstanceNameStoreTests',
        'GenForm.test.store.ProductSubstanceStoreTests',*/
        'GenForm.test.store.EnvironmentStoreTests'/*,
        'GenForm.test.view.component.SaveCancelToolbarTests',
        'GenForm.test.view.component.KeyValueComboTests',
        'GenForm.test.view.ProductSubstanceGridTests',
        'GenForm.test.view.SaveCancelWindowTests',
        'GenForm.test.view.LoginWindowTests',
        'GenForm.test.view.EnvironmentWindowTests',
        'GenForm.test.view.ProductSubstanceFormTests',
        'GenForm.test.view.ProductFormTests',
        'GenForm.test.view.BrandNameFormTests',
        'GenForm.test.view.BrandNameWindowTests'*/
    ]
});