<?xml version="1.0" encoding="utf-8"?>
<Database Name="Formularium2010" Class="FormulariaDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=HAL-2008;Initial Catalog=Formularium2010;Integrated Security=True" SettingsObjectName="Informedica.GenForm.Database.ORM.Properties.Settings" SettingsPropertyName="Formularium2010ConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.Formularium" Member="Formulariums">
    <Type Name="Formularium">
      <Column Name="formulariumId" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="naam" Type="System.String" DbType="NVarChar(125) NOT NULL" CanBeNull="false" />
      <Column Name="versieTimeStamp" Type="System.Data.Linq.Binary" DbType="rowversion NOT NULL" CanBeNull="false" IsVersion="true" />
      <Column Name="apotheekId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="hoofdauteur" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="Formularium_FormulariumAuteur" Member="FormulariumAuteurs" ThisKey="formulariumId" OtherKey="formulariumId" Type="FormulariumAuteur" />
      <Association Name="Formularium_FormulariumTekst" Member="FormulariumTeksts" ThisKey="formulariumId" OtherKey="formulariumId" Type="FormulariumTekst" />
      <Association Name="Formularium_ToepassingGroep" Member="ToepassingGroeps" ThisKey="formulariumId" OtherKey="formulariumId" Type="ToepassingGroep" />
      <Association Name="Formularium_ToepassingBijzonderheid" Member="ToepassingBijzonderheids" ThisKey="formulariumId" OtherKey="formulariumId" Type="ToepassingBijzonderheid" />
      <Association Name="Formularium_ArtikelBijzonderheid" Member="ArtikelBijzonderheids" ThisKey="formulariumId" OtherKey="formulariumId" Type="ArtikelBijzonderheid" />
      <Association Name="Formularium_GeneriekBijzonderheid" Member="GeneriekBijzonderheids" ThisKey="formulariumId" OtherKey="formulariumId" Type="GeneriekBijzonderheid" />
      <Association Name="Formularium_GeneriekDosering" Member="GeneriekDoserings" ThisKey="formulariumId" OtherKey="formulariumId" Type="GeneriekDosering" />
    </Type>
  </Table>
  <Table Name="dbo.FormulariumAuteur" Member="FormulariumAuteurs">
    <Type Name="FormulariumAuteur">
      <Column Name="formulariumAuteurId" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="auteur" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="formulariumId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="Formularium_FormulariumAuteur" Member="Formularium" ThisKey="formulariumId" OtherKey="formulariumId" Type="Formularium" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.FormulariumTekst" Member="FormulariumTeksts">
    <Type Name="FormulariumTekst">
      <Column Name="formulariumTekstId" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="formulariumId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="tekstItemId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="Formularium_FormulariumTekst" Member="Formularium" ThisKey="formulariumId" OtherKey="formulariumId" Type="Formularium" IsForeignKey="true" />
      <Association Name="TekstItem_FormulariumTekst" Member="TekstItem" ThisKey="tekstItemId" OtherKey="tekstItemId" Type="TekstItem" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.ToepassingGroep" Member="ToepassingGroeps">
    <Type Name="ToepassingGroep">
      <Column Name="toepassingGroepId" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="naam" Type="System.String" DbType="NChar(125) NOT NULL" CanBeNull="false" />
      <Column Name="versieTimeStamp" Type="System.Data.Linq.Binary" DbType="rowversion NOT NULL" CanBeNull="false" IsVersion="true" />
      <Column Name="formulariumId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="hoofdGroep" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="ToepassingGroep_ToepassingGroep" Member="ToepassingGroeps" ThisKey="toepassingGroepId" OtherKey="hoofdGroep" Type="ToepassingGroep" />
      <Association Name="ToepassingGroep_ToepassingBijzonderheid" Member="ToepassingBijzonderheids" ThisKey="toepassingGroepId" OtherKey="toepassingGroepId" Type="ToepassingBijzonderheid" />
      <Association Name="ToepassingGroep_DoseringToepassing" Member="DoseringToepassings" ThisKey="toepassingGroepId" OtherKey="toepassingGroepId" Type="DoseringToepassing" />
      <Association Name="Formularium_ToepassingGroep" Member="Formularium" ThisKey="formulariumId" OtherKey="formulariumId" Type="Formularium" IsForeignKey="true" />
      <Association Name="ToepassingGroep_ToepassingGroep" Member="ToepassingGroep1" ThisKey="hoofdGroep" OtherKey="toepassingGroepId" Type="ToepassingGroep" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.ToepassingBijzonderheid" Member="ToepassingBijzonderheids">
    <Type Name="ToepassingBijzonderheid">
      <Column Name="toepassingBijzonderheidId" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="toepassingGroepId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="formulariumId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="tekstItemId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="ToepassingGroep_ToepassingBijzonderheid" Member="ToepassingGroep" ThisKey="toepassingGroepId" OtherKey="toepassingGroepId" Type="ToepassingGroep" IsForeignKey="true" />
      <Association Name="Formularium_ToepassingBijzonderheid" Member="Formularium" ThisKey="formulariumId" OtherKey="formulariumId" Type="Formularium" IsForeignKey="true" />
      <Association Name="TekstItem_ToepassingBijzonderheid" Member="TekstItem" ThisKey="tekstItemId" OtherKey="tekstItemId" Type="TekstItem" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.ArtikelBijzonderheid" Member="ArtikelBijzonderheids">
    <Type Name="ArtikelBijzonderheid">
      <Column Name="artikelBijzonderheidId" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="artikelId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="formulariumId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="tekstItemId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="Formularium_ArtikelBijzonderheid" Member="Formularium" ThisKey="formulariumId" OtherKey="formulariumId" Type="Formularium" IsForeignKey="true" />
      <Association Name="TekstItem_ArtikelBijzonderheid" Member="TekstItem" ThisKey="tekstItemId" OtherKey="tekstItemId" Type="TekstItem" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.GeneriekBijzonderheid" Member="GeneriekBijzonderheids">
    <Type Name="GeneriekBijzonderheid">
      <Column Name="generiekBijzonderheidId" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="generiekId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="formulariumId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="tekstItemId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="Formularium_GeneriekBijzonderheid" Member="Formularium" ThisKey="formulariumId" OtherKey="formulariumId" Type="Formularium" IsForeignKey="true" />
      <Association Name="TekstItem_GeneriekBijzonderheid" Member="TekstItem" ThisKey="tekstItemId" OtherKey="tekstItemId" Type="TekstItem" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.GeneriekDosering" Member="GeneriekDoserings">
    <Type Name="GeneriekDosering">
      <Column Name="generiekDoseringId" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="versieTimeStamp" Type="System.Data.Linq.Binary" DbType="rowversion NOT NULL" CanBeNull="false" IsVersion="true" />
      <Column Name="tekstItemId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="generiekId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="formulariumId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="GeneriekDosering_DoseringArtikel" Member="DoseringArtikels" ThisKey="generiekDoseringId" OtherKey="generiekDoseringId" Type="DoseringArtikel" />
      <Association Name="GeneriekDosering_DoseringRoute" Member="DoseringRoutes" ThisKey="generiekDoseringId" OtherKey="generiekDoseringId" Type="DoseringRoute" />
      <Association Name="GeneriekDosering_DoseringToepassing" Member="DoseringToepassings" ThisKey="generiekDoseringId" OtherKey="generiekDoseringId" Type="DoseringToepassing" />
      <Association Name="Formularium_GeneriekDosering" Member="Formularium" ThisKey="formulariumId" OtherKey="formulariumId" Type="Formularium" IsForeignKey="true" />
      <Association Name="TekstItem_GeneriekDosering" Member="TekstItem" ThisKey="tekstItemId" OtherKey="tekstItemId" Type="TekstItem" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.DoseringArtikel" Member="DoseringArtikels">
    <Type Name="DoseringArtikel">
      <Column Name="doseringArtikelId" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="generiekDoseringId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="artikelId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="GeneriekDosering_DoseringArtikel" Member="GeneriekDosering" ThisKey="generiekDoseringId" OtherKey="generiekDoseringId" Type="GeneriekDosering" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.DoseringRoute" Member="DoseringRoutes">
    <Type Name="DoseringRoute">
      <Column Name="doseringRouteId" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="generiekDoseringId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="routeId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="GeneriekDosering_DoseringRoute" Member="GeneriekDosering" ThisKey="generiekDoseringId" OtherKey="generiekDoseringId" Type="GeneriekDosering" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.DoseringToepassing" Member="DoseringToepassings">
    <Type Name="DoseringToepassing">
      <Column Name="doseringToepassingId" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="generiekDoseringId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="toepassingGroepId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="GeneriekDosering_DoseringToepassing" Member="GeneriekDosering" ThisKey="generiekDoseringId" OtherKey="generiekDoseringId" Type="GeneriekDosering" IsForeignKey="true" />
      <Association Name="ToepassingGroep_DoseringToepassing" Member="ToepassingGroep" ThisKey="toepassingGroepId" OtherKey="toepassingGroepId" Type="ToepassingGroep" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.TekstItem" Member="TekstItems">
    <Type Name="TekstItem">
      <Column Name="tekstItemId" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="versieTimeStamp" Type="System.Data.Linq.Binary" DbType="rowversion NOT NULL" CanBeNull="false" IsVersion="true" />
      <Column Name="tekst" Type="System.String" DbType="NVarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="tekstType" Type="System.String" DbType="NChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="tekstStatus" Type="System.String" DbType="NChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="tekstKop" Type="System.String" DbType="NChar(125)" CanBeNull="true" />
      <Association Name="TekstItem_FormulariumTekst" Member="FormulariumTeksts" ThisKey="tekstItemId" OtherKey="tekstItemId" Type="FormulariumTekst" />
      <Association Name="TekstItem_ToepassingBijzonderheid" Member="ToepassingBijzonderheids" ThisKey="tekstItemId" OtherKey="tekstItemId" Type="ToepassingBijzonderheid" />
      <Association Name="TekstItem_ArtikelBijzonderheid" Member="ArtikelBijzonderheids" ThisKey="tekstItemId" OtherKey="tekstItemId" Type="ArtikelBijzonderheid" />
      <Association Name="TekstItem_GeneriekBijzonderheid" Member="GeneriekBijzonderheids" ThisKey="tekstItemId" OtherKey="tekstItemId" Type="GeneriekBijzonderheid" />
      <Association Name="TekstItem_GeneriekDosering" Member="GeneriekDoserings" ThisKey="tekstItemId" OtherKey="tekstItemId" Type="GeneriekDosering" />
    </Type>
  </Table>
</Database>