<?xml version="1.0" encoding="utf-8"?><Database Name="FormulariumArthur" Class="FormulariumImportDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=hal-2008;Initial Catalog=FormulariumArthur;Integrated Security=True" SettingsObjectName="Informedica.GenForm.Database.Properties.Settings" SettingsPropertyName="FormulariumArthurConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.Doseringsadvies" Member="Doseringsadvies">
    <Type Name="Doseringsadvies">
      <Column Name="doseringsadviesId" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="adviestekst" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Association Name="Doseringsadvies_PreparaatDoseringsadvies" Member="PreparaatDoseringsadvies" ThisKey="doseringsadviesId" OtherKey="doseringsadviesId" Type="PreparaatDoseringsadvies" />
      <Association Name="Doseringsadvies_DoseringsadviesToedieningswijze" Member="DoseringsadviesToedieningswijze" ThisKey="doseringsadviesId" OtherKey="doseringsadviesId" Type="DoseringsadviesToedieningswijze" />
      <Association Name="Doseringsadvies_DoseringsadviesToepassingsgroep" Member="DoseringsadviesToepassingsgroep" ThisKey="doseringsadviesId" OtherKey="doseringsadviesId" Type="DoseringsadviesToepassingsgroep" />
    </Type>
  </Table>
  <Table Name="dbo.PreparaatDoseringsadvies" Member="PreparaatDoseringsadvies">
    <Type Name="PreparaatDoseringsadvies">
      <Column Name="preparaatName" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="doseringsadviesId" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="preparaatName_ID" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Association Name="Doseringsadvies_PreparaatDoseringsadvies" Member="Doseringsadvies" ThisKey="doseringsadviesId" OtherKey="doseringsadviesId" Type="Doseringsadvies" IsForeignKey="true" />
      <Association Name="Preparaat_PreparaatDoseringsadvies" Member="Preparaat" ThisKey="preparaatName_ID" OtherKey="preparaatName_ID" Type="Preparaat" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.PreparaatStof" Member="PreparaatStof">
    <Type Name="PreparaatStof">
      <Column Name="preparaatName" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="stofName" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="preparaatName_ID" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="stofName_ID" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Association Name="Preparaat_PreparaatStof" Member="Preparaat" ThisKey="preparaatName_ID" OtherKey="preparaatName_ID" Type="Preparaat" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.PreparaatToepassingsgroep" Member="PreparaatToepassingsgroep">
    <Type Name="PreparaatToepassingsgroep">
      <Column Name="preparaatName" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="toepassingsgroepName" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="preparaatName_ID" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="toepassingsgroepName_ID" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Association Name="Preparaat_PreparaatToepassingsgroep" Member="Preparaat" ThisKey="preparaatName_ID" OtherKey="preparaatName_ID" Type="Preparaat" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.PreparaatToediening" Member="PreparaatToediening">
    <Type Name="PreparaatToediening">
      <Column Name="toedieningswijze" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="preparaatName" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="preparaatName_ID" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="toedieningswijze_ID" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Association Name="Preparaat_PreparaatToediening" Member="Preparaat" ThisKey="preparaatName_ID" OtherKey="preparaatName_ID" Type="Preparaat" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Preparaat" Member="Preparaat">
    <Type Name="Preparaat">
      <Column Name="preparaatName" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="prijs" Type="System.Decimal" DbType="Decimal(19,4)" CanBeNull="true" />
      <Column Name="aflevervorm" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="merk" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="toedieningsvorm" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="gebruiksnaam" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="preparaatName_ID" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Association Name="Preparaat_PreparaatDoseringsadvies" Member="PreparaatDoseringsadvies" ThisKey="preparaatName_ID" OtherKey="preparaatName_ID" Type="PreparaatDoseringsadvies" />
      <Association Name="Preparaat_PreparaatStof" Member="PreparaatStof" ThisKey="preparaatName_ID" OtherKey="preparaatName_ID" Type="PreparaatStof" />
      <Association Name="Preparaat_PreparaatToepassingsgroep" Member="PreparaatToepassingsgroep" ThisKey="preparaatName_ID" OtherKey="preparaatName_ID" Type="PreparaatToepassingsgroep" />
      <Association Name="Preparaat_PreparaatToediening" Member="PreparaatToediening" ThisKey="preparaatName_ID" OtherKey="preparaatName_ID" Type="PreparaatToediening" />
    </Type>
  </Table>
  <Table Name="dbo.DoseringsadviesToedieningswijze" Member="DoseringsadviesToedieningswijze">
    <Type Name="DoseringsadviesToedieningswijze">
      <Column Name="toedieningswijze" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="doseringsadviesId" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="toedieningswijze_ID" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Association Name="Doseringsadvies_DoseringsadviesToedieningswijze" Member="Doseringsadvies" ThisKey="doseringsadviesId" OtherKey="doseringsadviesId" Type="Doseringsadvies" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.DoseringsadviesToepassingsgroep" Member="DoseringsadviesToepassingsgroep">
    <Type Name="DoseringsadviesToepassingsgroep">
      <Column Name="doseringsadviesId" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="toepassingsgroepName" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="toepassingsgroepName_ID" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Association Name="Doseringsadvies_DoseringsadviesToepassingsgroep" Member="Doseringsadvies" ThisKey="doseringsadviesId" OtherKey="doseringsadviesId" Type="Doseringsadvies" IsForeignKey="true" />
    </Type>
  </Table>
</Database>