<?xml version="1.0" encoding="utf-8"?>
<Database Name="Formularium2010" Class="ProductsDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=hal-2008;Initial Catalog=Formularium2010;Integrated Security=True" SettingsObjectName="Informedica.GenForm.Database.ORM.Properties.Settings" SettingsPropertyName="Formularium2010ConnectionString1" Provider="System.Data.SqlClient" />
  <Table Name="dbo.Artikel" Member="Artikels">
    <Type Name="Artikel">
      <Column Name="artikelId" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="naam" Type="System.String" DbType="NChar(125) NOT NULL" CanBeNull="false" />
      <Column Name="versieTimeStamp" Type="System.Data.Linq.Binary" DbType="rowversion NOT NULL" CanBeNull="false" IsVersion="true" />
      <Column Name="generiekId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="ArtikelGUID" Type="System.String" DbType="NChar(125)" CanBeNull="true" />
      <Column Name="HPKode" Type="System.String" DbType="NChar(125)" CanBeNull="true" />
      <Column Name="defaultNaam" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="KAE" Type="System.Single" DbType="Real" CanBeNull="true" />
      <Column Name="isCombinatie" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="ATKode" Type="System.String" DbType="NChar(125)" CanBeNull="true" />
      <Column Name="hoeveelheid" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="eenheidId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="toedienVormId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="verpakkingId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="merkId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="Artikel_ArtikelRoute" Member="ArtikelRoutes" ThisKey="artikelId" OtherKey="artikelId" Type="ArtikelRoute" />
      <Association Name="Artikel_ArtikelGeneriek" Member="ArtikelGenerieks" ThisKey="artikelId" OtherKey="artikelId" Type="ArtikelGeneriek" />
      <Association Name="Generiek_Artikel" Member="Generiek" ThisKey="generiekId" OtherKey="generiekId" Type="Generiek" IsForeignKey="true" />
      <Association Name="Verpakking_Artikel" Member="Verpakking" ThisKey="verpakkingId" OtherKey="verpakkingId" Type="Verpakking" IsForeignKey="true" />
      <Association Name="ToedienVorm_Artikel" Member="ToedienVorm" ThisKey="toedienVormId" OtherKey="toedienVormId" Type="ToedienVorm" IsForeignKey="true" />
      <Association Name="Eenheid_Artikel" Member="Eenheid" ThisKey="eenheidId" OtherKey="eenheidId" Type="Eenheid" IsForeignKey="true" />
      <Association Name="Merk_Artikel" Member="Merk" ThisKey="merkId" OtherKey="merkId" Type="Merk" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.ArtikelRoute" Member="ArtikelRoutes">
    <Type Name="ArtikelRoute">
      <Column Name="artikelRouteId" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="artikelId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="routeId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="Artikel_ArtikelRoute" Member="Artikel" ThisKey="artikelId" OtherKey="artikelId" Type="Artikel" IsForeignKey="true" />
      <Association Name="Route_ArtikelRoute" Member="Route" ThisKey="routeId" OtherKey="routeId" Type="Route" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Route" Member="Routes">
    <Type Name="Route">
      <Column Name="routeId" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="naam" Type="System.String" DbType="NChar(125) NOT NULL" CanBeNull="false" />
      <Column Name="versieTimeStamp" Type="System.Data.Linq.Binary" DbType="rowversion NOT NULL" CanBeNull="false" IsVersion="true" />
      <Association Name="Route_ArtikelRoute" Member="ArtikelRoutes" ThisKey="routeId" OtherKey="routeId" Type="ArtikelRoute" />
      <Association Name="Route_ToedienVormRoute" Member="ToedienVormRoutes" ThisKey="routeId" OtherKey="routeId" Type="ToedienVormRoute" />
    </Type>
  </Table>
  <Table Name="dbo.ArtikelGeneriek" Member="ArtikelGenerieks">
    <Type Name="ArtikelGeneriek">
      <Column Name="artikelGeneriekId" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="volgorde" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="artikelId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="generiekId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="sterkte" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="hoeveelheid" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="eenheidId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="Artikel_ArtikelGeneriek" Member="Artikel" ThisKey="artikelId" OtherKey="artikelId" Type="Artikel" IsForeignKey="true" />
      <Association Name="Generiek_ArtikelGeneriek" Member="Generiek" ThisKey="generiekId" OtherKey="generiekId" Type="Generiek" IsForeignKey="true" />
      <Association Name="Eenheid_ArtikelGeneriek" Member="Eenheid" ThisKey="eenheidId" OtherKey="eenheidId" Type="Eenheid" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Generiek" Member="Generieks">
    <Type Name="Generiek">
      <Column Name="generiekId" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="naam" Type="System.String" DbType="NChar(125) NOT NULL" CanBeNull="false" />
      <Column Name="versieTimeStamp" Type="System.Data.Linq.Binary" DbType="rowversion NOT NULL" CanBeNull="false" IsVersion="true" />
      <Column Name="code" Type="System.String" DbType="NChar(125)" CanBeNull="true" />
      <Column Name="isStof" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="generiekGroepId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="Generiek_Artikel" Member="Artikels" ThisKey="generiekId" OtherKey="generiekId" Type="Artikel" />
      <Association Name="Generiek_ArtikelGeneriek" Member="ArtikelGenerieks" ThisKey="generiekId" OtherKey="generiekId" Type="ArtikelGeneriek" />
      <Association Name="GeneriekGroep_Generiek" Member="GeneriekGroep" ThisKey="generiekGroepId" OtherKey="generiekGroepId" Type="GeneriekGroep" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Verpakking" Member="Verpakkings">
    <Type Name="Verpakking">
      <Column Name="verpakkingId" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="naam" Type="System.String" DbType="NChar(125) NOT NULL" CanBeNull="false" />
      <Column Name="versieTimeStamp" Type="System.Data.Linq.Binary" DbType="rowversion NOT NULL" CanBeNull="false" IsVersion="true" />
      <Association Name="Verpakking_Artikel" Member="Artikels" ThisKey="verpakkingId" OtherKey="verpakkingId" Type="Artikel" />
      <Association Name="Verpakking_ToedienVormVerpakking" Member="ToedienVormVerpakkings" ThisKey="verpakkingId" OtherKey="verpakkingId" Type="ToedienVormVerpakking" />
    </Type>
  </Table>
  <Table Name="dbo.ToedienVorm" Member="ToedienVorms">
    <Type Name="ToedienVorm">
      <Column Name="toedienVormId" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="naam" Type="System.String" DbType="NChar(125) NOT NULL" CanBeNull="false" />
      <Column Name="versieTimeStamp" Type="System.Data.Linq.Binary" DbType="rowversion NOT NULL" CanBeNull="false" IsVersion="true" />
      <Association Name="ToedienVorm_Artikel" Member="Artikels" ThisKey="toedienVormId" OtherKey="toedienVormId" Type="Artikel" />
      <Association Name="ToedienVorm_ToedienVormRoute" Member="ToedienVormRoutes" ThisKey="toedienVormId" OtherKey="toedienVormId" Type="ToedienVormRoute" />
      <Association Name="ToedienVorm_ToedienVormVerpakking" Member="ToedienVormVerpakkings" ThisKey="toedienVormId" OtherKey="toedienVormId" Type="ToedienVormVerpakking" />
      <Association Name="ToedienVorm_ToedienVormEenheid" Member="ToedienVormEenheids" ThisKey="toedienVormId" OtherKey="toedienVormId" Type="ToedienVormEenheid" />
    </Type>
  </Table>
  <Table Name="dbo.ToedienVormRoute" Member="ToedienVormRoutes">
    <Type Name="ToedienVormRoute">
      <Column Name="toedienVormRouteId" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="toedienVormId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="routeId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="ToedienVorm_ToedienVormRoute" Member="ToedienVorm" ThisKey="toedienVormId" OtherKey="toedienVormId" Type="ToedienVorm" IsForeignKey="true" />
      <Association Name="Route_ToedienVormRoute" Member="Route" ThisKey="routeId" OtherKey="routeId" Type="Route" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.ToedienVormVerpakking" Member="ToedienVormVerpakkings">
    <Type Name="ToedienVormVerpakking">
      <Column Name="toedienVormVerpakkingId" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="toedienVormId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="verpakkingId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="ToedienVorm_ToedienVormVerpakking" Member="ToedienVorm" ThisKey="toedienVormId" OtherKey="toedienVormId" Type="ToedienVorm" IsForeignKey="true" />
      <Association Name="Verpakking_ToedienVormVerpakking" Member="Verpakking" ThisKey="verpakkingId" OtherKey="verpakkingId" Type="Verpakking" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Eenheid" Member="Eenheids">
    <Type Name="Eenheid">
      <Column Name="eenheidId" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="naam" Type="System.String" DbType="NChar(125) NOT NULL" CanBeNull="false" />
      <Column Name="versieTimeStamp" Type="System.Data.Linq.Binary" DbType="rowversion NOT NULL" CanBeNull="false" IsVersion="true" />
      <Column Name="eenheidGroepId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="afkorting" Type="System.String" DbType="NChar(125)" CanBeNull="true" />
      <Column Name="factor" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="KAE" Type="System.Single" DbType="Real" CanBeNull="true" />
      <Column Name="isReferentie" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Association Name="Eenheid_Artikel" Member="Artikels" ThisKey="eenheidId" OtherKey="eenheidId" Type="Artikel" />
      <Association Name="Eenheid_ArtikelGeneriek" Member="ArtikelGenerieks" ThisKey="eenheidId" OtherKey="eenheidId" Type="ArtikelGeneriek" />
      <Association Name="Eenheid_ToedienVormEenheid" Member="ToedienVormEenheids" ThisKey="eenheidId" OtherKey="eenheidId" Type="ToedienVormEenheid" />
      <Association Name="EenheidGroep_Eenheid" Member="EenheidGroep" ThisKey="eenheidGroepId" OtherKey="eenheidGroepId" Type="EenheidGroep" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.EenheidGroep" Member="EenheidGroeps">
    <Type Name="EenheidGroep">
      <Column Name="eenheidGroepId" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="versieTimeStamp" Type="System.Data.Linq.Binary" DbType="rowversion NOT NULL" CanBeNull="false" IsVersion="true" />
      <Column Name="naam" Type="System.String" DbType="NChar(125) NOT NULL" CanBeNull="false" />
      <Column Name="conversieToestaan" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Association Name="EenheidGroep_Eenheid" Member="Eenheids" ThisKey="eenheidGroepId" OtherKey="eenheidGroepId" Type="Eenheid" />
    </Type>
  </Table>
  <Table Name="dbo.GeneriekGroep" Member="GeneriekGroeps">
    <Type Name="GeneriekGroep">
      <Column Name="generiekGroepId" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="naam" Type="System.String" DbType="NChar(125) NOT NULL" CanBeNull="false" />
      <Column Name="versieTimeStamp" Type="System.Data.Linq.Binary" DbType="rowversion NOT NULL" CanBeNull="false" IsVersion="true" />
      <Column Name="hoofdGroep" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="GeneriekGroep_Generiek" Member="Generieks" ThisKey="generiekGroepId" OtherKey="generiekGroepId" Type="Generiek" />
      <Association Name="GeneriekGroep_GeneriekGroep" Member="GeneriekGroeps" ThisKey="generiekGroepId" OtherKey="hoofdGroep" Type="GeneriekGroep" />
      <Association Name="GeneriekGroep_GeneriekGroep" Member="GeneriekGroep1" ThisKey="hoofdGroep" OtherKey="generiekGroepId" Type="GeneriekGroep" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Merk" Member="Merks">
    <Type Name="Merk">
      <Column Name="merkId" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="naam" Type="System.String" DbType="NChar(125) NOT NULL" CanBeNull="false" />
      <Column Name="versieTimeStamp" Type="System.Data.Linq.Binary" DbType="rowversion NOT NULL" CanBeNull="false" IsVersion="true" />
      <Association Name="Merk_Artikel" Member="Artikels" ThisKey="merkId" OtherKey="merkId" Type="Artikel" />
    </Type>
  </Table>
  <Table Name="dbo.ToedienVormEenheid" Member="ToedienVormEenheids">
    <Type Name="ToedienVormEenheid">
      <Column Name="toedienVormEenheidId" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="toedienVormId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="eenheidId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="ToedienVorm_ToedienVormEenheid" Member="ToedienVorm" ThisKey="toedienVormId" OtherKey="toedienVormId" Type="ToedienVorm" IsForeignKey="true" />
      <Association Name="Eenheid_ToedienVormEenheid" Member="Eenheid" ThisKey="eenheidId" OtherKey="eenheidId" Type="Eenheid" IsForeignKey="true" />
    </Type>
  </Table>
  <Function Name="dbo.CSLA_Artikel_Delete" Method="CSLA_Artikel_Delete">
    <Parameter Name="p_artikelId" Type="System.Int32" DbType="Int" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.CSLA_Artikel_Insert" Method="CSLA_Artikel_Insert">
    <Parameter Name="p_versieTimeStamp" Type="System.Data.Linq.Binary" DbType="Timestamp" Direction="InOut" />
    <Parameter Name="p_naam" Type="System.String" DbType="NChar(125)" />
    <Parameter Name="p_generiekId" Type="System.Int32" DbType="Int" />
    <Parameter Name="p_ArtikelGUID" Type="System.String" DbType="NChar(125)" />
    <Parameter Name="p_HPKode" Type="System.String" DbType="NChar(125)" />
    <Parameter Name="p_defaultNaam" Type="System.String" DbType="NVarChar(MAX)" />
    <Parameter Name="p_KAE" Type="System.Single" DbType="Real" />
    <Parameter Name="p_isCombinatie" Type="System.Boolean" DbType="Bit" />
    <Parameter Name="p_ATKode" Type="System.String" DbType="NChar(125)" />
    <Parameter Name="p_hoeveelheid" Type="System.Double" DbType="Float" />
    <Parameter Name="p_eenheidId" Type="System.Int32" DbType="Int" />
    <Parameter Name="p_toedienVormId" Type="System.Int32" DbType="Int" />
    <Parameter Name="p_verpakkingId" Type="System.Int32" DbType="Int" />
    <Parameter Name="p_merkId" Type="System.Int32" DbType="Int" />
    <Parameter Name="p_artikelId" Type="System.Int32" DbType="Int" Direction="InOut" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.CSLA_Artikel_Select" Method="CSLA_Artikel_Select">
    <Parameter Name="p_artikelId" Type="System.Int32" DbType="Int" />
    <Parameter Name="p_naam" Type="System.String" DbType="NChar(125)" />
    <Parameter Name="p_generiekId" Type="System.Int32" DbType="Int" />
    <Parameter Name="p_ArtikelGUID" Type="System.String" DbType="NChar(125)" />
    <Parameter Name="p_ArtikelGUIDHasValue" Type="System.Boolean" DbType="Bit" />
    <Parameter Name="p_HPKode" Type="System.String" DbType="NChar(125)" />
    <Parameter Name="p_HPKodeHasValue" Type="System.Boolean" DbType="Bit" />
    <Parameter Name="p_defaultNaam" Type="System.String" DbType="NVarChar(MAX)" />
    <Parameter Name="p_defaultNaamHasValue" Type="System.Boolean" DbType="Bit" />
    <Parameter Name="p_KAE" Type="System.Single" DbType="Real" />
    <Parameter Name="p_KAEHasValue" Type="System.Boolean" DbType="Bit" />
    <Parameter Name="p_isCombinatie" Type="System.Boolean" DbType="Bit" />
    <Parameter Name="p_isCombinatieHasValue" Type="System.Boolean" DbType="Bit" />
    <Parameter Name="p_ATKode" Type="System.String" DbType="NChar(125)" />
    <Parameter Name="p_ATKodeHasValue" Type="System.Boolean" DbType="Bit" />
    <Parameter Name="p_hoeveelheid" Type="System.Double" DbType="Float" />
    <Parameter Name="p_hoeveelheidHasValue" Type="System.Boolean" DbType="Bit" />
    <Parameter Name="p_eenheidId" Type="System.Int32" DbType="Int" />
    <Parameter Name="p_eenheidIdHasValue" Type="System.Boolean" DbType="Bit" />
    <Parameter Name="p_toedienVormId" Type="System.Int32" DbType="Int" />
    <Parameter Name="p_toedienVormIdHasValue" Type="System.Boolean" DbType="Bit" />
    <Parameter Name="p_verpakkingId" Type="System.Int32" DbType="Int" />
    <Parameter Name="p_verpakkingIdHasValue" Type="System.Boolean" DbType="Bit" />
    <Parameter Name="p_merkId" Type="System.Int32" DbType="Int" />
    <Parameter Name="p_merkIdHasValue" Type="System.Boolean" DbType="Bit" />
    <ElementType Name="CSLA_Artikel_SelectResult">
      <Column Name="artikelId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="naam" Type="System.String" DbType="NChar(125) NOT NULL" CanBeNull="false" />
      <Column Name="versieTimeStamp" Type="System.Data.Linq.Binary" DbType="rowversion NOT NULL" CanBeNull="false" />
      <Column Name="generiekId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="ArtikelGUID" Type="System.String" DbType="NChar(125)" CanBeNull="true" />
      <Column Name="HPKode" Type="System.String" DbType="NChar(125)" CanBeNull="true" />
      <Column Name="defaultNaam" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="KAE" Type="System.Single" DbType="Real" CanBeNull="true" />
      <Column Name="isCombinatie" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="ATKode" Type="System.String" DbType="NChar(125)" CanBeNull="true" />
      <Column Name="hoeveelheid" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="eenheidId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="toedienVormId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="verpakkingId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="merkId" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.CSLA_Artikel_Update" Method="CSLA_Artikel_Update">
    <Parameter Name="p_versieTimeStamp" Type="System.Data.Linq.Binary" DbType="Timestamp" Direction="InOut" />
    <Parameter Name="p_artikelId" Type="System.Int32" DbType="Int" />
    <Parameter Name="p_naam" Type="System.String" DbType="NChar(125)" />
    <Parameter Name="p_generiekId" Type="System.Int32" DbType="Int" />
    <Parameter Name="p_ArtikelGUID" Type="System.String" DbType="NChar(125)" />
    <Parameter Name="p_HPKode" Type="System.String" DbType="NChar(125)" />
    <Parameter Name="p_defaultNaam" Type="System.String" DbType="NVarChar(MAX)" />
    <Parameter Name="p_KAE" Type="System.Single" DbType="Real" />
    <Parameter Name="p_isCombinatie" Type="System.Boolean" DbType="Bit" />
    <Parameter Name="p_ATKode" Type="System.String" DbType="NChar(125)" />
    <Parameter Name="p_hoeveelheid" Type="System.Double" DbType="Float" />
    <Parameter Name="p_eenheidId" Type="System.Int32" DbType="Int" />
    <Parameter Name="p_toedienVormId" Type="System.Int32" DbType="Int" />
    <Parameter Name="p_verpakkingId" Type="System.Int32" DbType="Int" />
    <Parameter Name="p_merkId" Type="System.Int32" DbType="Int" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.CSLA_ArtikelGeneriek_Delete" Method="CSLA_ArtikelGeneriek_Delete">
    <Parameter Name="p_artikelGeneriekId" Type="System.Int32" DbType="Int" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.CSLA_ArtikelGeneriek_Insert" Method="CSLA_ArtikelGeneriek_Insert">
    <Parameter Name="p_volgorde" Type="System.Int32" DbType="Int" />
    <Parameter Name="p_artikelId" Type="System.Int32" DbType="Int" />
    <Parameter Name="p_generiekId" Type="System.Int32" DbType="Int" />
    <Parameter Name="p_sterkte" Type="System.Double" DbType="Float" />
    <Parameter Name="p_hoeveelheid" Type="System.Double" DbType="Float" />
    <Parameter Name="p_eenheidId" Type="System.Int32" DbType="Int" />
    <Parameter Name="p_artikelGeneriekId" Type="System.Int32" DbType="Int" Direction="InOut" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.CSLA_ArtikelGeneriek_Select" Method="CSLA_ArtikelGeneriek_Select">
    <Parameter Name="p_artikelGeneriekId" Type="System.Int32" DbType="Int" />
    <Parameter Name="p_volgorde" Type="System.Int32" DbType="Int" />
    <Parameter Name="p_artikelId" Type="System.Int32" DbType="Int" />
    <Parameter Name="p_generiekId" Type="System.Int32" DbType="Int" />
    <Parameter Name="p_sterkte" Type="System.Double" DbType="Float" />
    <Parameter Name="p_sterkteHasValue" Type="System.Boolean" DbType="Bit" />
    <Parameter Name="p_hoeveelheid" Type="System.Double" DbType="Float" />
    <Parameter Name="p_hoeveelheidHasValue" Type="System.Boolean" DbType="Bit" />
    <Parameter Name="p_eenheidId" Type="System.Int32" DbType="Int" />
    <Parameter Name="p_eenheidIdHasValue" Type="System.Boolean" DbType="Bit" />
    <ElementType Name="CSLA_ArtikelGeneriek_SelectResult">
      <Column Name="artikelGeneriekId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="volgorde" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="artikelId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="generiekId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="sterkte" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="hoeveelheid" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="eenheidId" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.CSLA_ArtikelGeneriek_Update" Method="CSLA_ArtikelGeneriek_Update">
    <Parameter Name="p_artikelGeneriekId" Type="System.Int32" DbType="Int" />
    <Parameter Name="p_volgorde" Type="System.Int32" DbType="Int" />
    <Parameter Name="p_artikelId" Type="System.Int32" DbType="Int" />
    <Parameter Name="p_generiekId" Type="System.Int32" DbType="Int" />
    <Parameter Name="p_sterkte" Type="System.Double" DbType="Float" />
    <Parameter Name="p_hoeveelheid" Type="System.Double" DbType="Float" />
    <Parameter Name="p_eenheidId" Type="System.Int32" DbType="Int" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.CSLA_ArtikelRoute_Delete" Method="CSLA_ArtikelRoute_Delete">
    <Parameter Name="p_artikelRouteId" Type="System.Int32" DbType="Int" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.CSLA_ArtikelRoute_Insert" Method="CSLA_ArtikelRoute_Insert">
    <Parameter Name="p_artikelId" Type="System.Int32" DbType="Int" />
    <Parameter Name="p_routeId" Type="System.Int32" DbType="Int" />
    <Parameter Name="p_artikelRouteId" Type="System.Int32" DbType="Int" Direction="InOut" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.CSLA_ArtikelRoute_Select" Method="CSLA_ArtikelRoute_Select">
    <Parameter Name="p_artikelRouteId" Type="System.Int32" DbType="Int" />
    <Parameter Name="p_artikelId" Type="System.Int32" DbType="Int" />
    <Parameter Name="p_routeId" Type="System.Int32" DbType="Int" />
    <ElementType Name="CSLA_ArtikelRoute_SelectResult">
      <Column Name="artikelRouteId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="artikelId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="routeId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
    </ElementType>
  </Function>
  <Function Name="dbo.CSLA_ArtikelRoute_Update" Method="CSLA_ArtikelRoute_Update">
    <Parameter Name="p_artikelRouteId" Type="System.Int32" DbType="Int" />
    <Parameter Name="p_artikelId" Type="System.Int32" DbType="Int" />
    <Parameter Name="p_routeId" Type="System.Int32" DbType="Int" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.CSLA_Eenheid_Delete" Method="CSLA_Eenheid_Delete">
    <Parameter Name="p_eenheidId" Type="System.Int32" DbType="Int" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.CSLA_Eenheid_Insert" Method="CSLA_Eenheid_Insert">
    <Parameter Name="p_versieTimeStamp" Type="System.Data.Linq.Binary" DbType="Timestamp" Direction="InOut" />
    <Parameter Name="p_naam" Type="System.String" DbType="NChar(125)" />
    <Parameter Name="p_eenheidGroepId" Type="System.Int32" DbType="Int" />
    <Parameter Name="p_afkorting" Type="System.String" DbType="NChar(125)" />
    <Parameter Name="p_factor" Type="System.Double" DbType="Float" />
    <Parameter Name="p_KAE" Type="System.Single" DbType="Real" />
    <Parameter Name="p_isReferentie" Type="System.Boolean" DbType="Bit" />
    <Parameter Name="p_eenheidId" Type="System.Int32" DbType="Int" Direction="InOut" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.CSLA_Eenheid_Select" Method="CSLA_Eenheid_Select">
    <Parameter Name="p_eenheidId" Type="System.Int32" DbType="Int" />
    <Parameter Name="p_naam" Type="System.String" DbType="NChar(125)" />
    <Parameter Name="p_eenheidGroepId" Type="System.Int32" DbType="Int" />
    <Parameter Name="p_afkorting" Type="System.String" DbType="NChar(125)" />
    <Parameter Name="p_afkortingHasValue" Type="System.Boolean" DbType="Bit" />
    <Parameter Name="p_factor" Type="System.Double" DbType="Float" />
    <Parameter Name="p_factorHasValue" Type="System.Boolean" DbType="Bit" />
    <Parameter Name="p_KAE" Type="System.Single" DbType="Real" />
    <Parameter Name="p_KAEHasValue" Type="System.Boolean" DbType="Bit" />
    <Parameter Name="p_isReferentie" Type="System.Boolean" DbType="Bit" />
    <Parameter Name="p_isReferentieHasValue" Type="System.Boolean" DbType="Bit" />
    <ElementType Name="CSLA_Eenheid_SelectResult">
      <Column Name="eenheidId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="naam" Type="System.String" DbType="NChar(125) NOT NULL" CanBeNull="false" />
      <Column Name="versieTimeStamp" Type="System.Data.Linq.Binary" DbType="rowversion NOT NULL" CanBeNull="false" />
      <Column Name="eenheidGroepId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="afkorting" Type="System.String" DbType="NChar(125)" CanBeNull="true" />
      <Column Name="factor" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="KAE" Type="System.Single" DbType="Real" CanBeNull="true" />
      <Column Name="isReferentie" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.CSLA_Eenheid_Update" Method="CSLA_Eenheid_Update">
    <Parameter Name="p_versieTimeStamp" Type="System.Data.Linq.Binary" DbType="Timestamp" Direction="InOut" />
    <Parameter Name="p_eenheidId" Type="System.Int32" DbType="Int" />
    <Parameter Name="p_naam" Type="System.String" DbType="NChar(125)" />
    <Parameter Name="p_eenheidGroepId" Type="System.Int32" DbType="Int" />
    <Parameter Name="p_afkorting" Type="System.String" DbType="NChar(125)" />
    <Parameter Name="p_factor" Type="System.Double" DbType="Float" />
    <Parameter Name="p_KAE" Type="System.Single" DbType="Real" />
    <Parameter Name="p_isReferentie" Type="System.Boolean" DbType="Bit" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.CSLA_EenheidGroep_Delete" Method="CSLA_EenheidGroep_Delete">
    <Parameter Name="p_eenheidGroepId" Type="System.Int32" DbType="Int" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.CSLA_EenheidGroep_Insert" Method="CSLA_EenheidGroep_Insert">
    <Parameter Name="p_versieTimeStamp" Type="System.Data.Linq.Binary" DbType="Timestamp" Direction="InOut" />
    <Parameter Name="p_naam" Type="System.String" DbType="NChar(125)" />
    <Parameter Name="p_conversieToestaan" Type="System.Boolean" DbType="Bit" />
    <Parameter Name="p_eenheidGroepId" Type="System.Int32" DbType="Int" Direction="InOut" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.CSLA_EenheidGroep_Select" Method="CSLA_EenheidGroep_Select">
    <Parameter Name="p_eenheidGroepId" Type="System.Int32" DbType="Int" />
    <Parameter Name="p_naam" Type="System.String" DbType="NChar(125)" />
    <Parameter Name="p_conversieToestaan" Type="System.Boolean" DbType="Bit" />
    <Parameter Name="p_conversieToestaanHasValue" Type="System.Boolean" DbType="Bit" />
    <ElementType Name="CSLA_EenheidGroep_SelectResult">
      <Column Name="eenheidGroepId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="versieTimeStamp" Type="System.Data.Linq.Binary" DbType="rowversion NOT NULL" CanBeNull="false" />
      <Column Name="naam" Type="System.String" DbType="NChar(125) NOT NULL" CanBeNull="false" />
      <Column Name="conversieToestaan" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.CSLA_EenheidGroep_Update" Method="CSLA_EenheidGroep_Update">
    <Parameter Name="p_versieTimeStamp" Type="System.Data.Linq.Binary" DbType="Timestamp" Direction="InOut" />
    <Parameter Name="p_eenheidGroepId" Type="System.Int32" DbType="Int" />
    <Parameter Name="p_naam" Type="System.String" DbType="NChar(125)" />
    <Parameter Name="p_conversieToestaan" Type="System.Boolean" DbType="Bit" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.CSLA_Generiek_Delete" Method="CSLA_Generiek_Delete">
    <Parameter Name="p_generiekId" Type="System.Int32" DbType="Int" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.CSLA_Generiek_Insert" Method="CSLA_Generiek_Insert">
    <Parameter Name="p_versieTimeStamp" Type="System.Data.Linq.Binary" DbType="Timestamp" Direction="InOut" />
    <Parameter Name="p_naam" Type="System.String" DbType="NChar(125)" />
    <Parameter Name="p_code" Type="System.String" DbType="NChar(125)" />
    <Parameter Name="p_isStof" Type="System.Boolean" DbType="Bit" />
    <Parameter Name="p_generiekGroepId" Type="System.Int32" DbType="Int" />
    <Parameter Name="p_generiekId" Type="System.Int32" DbType="Int" Direction="InOut" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.CSLA_Generiek_Select" Method="CSLA_Generiek_Select">
    <Parameter Name="p_generiekId" Type="System.Int32" DbType="Int" />
    <Parameter Name="p_naam" Type="System.String" DbType="NChar(125)" />
    <Parameter Name="p_code" Type="System.String" DbType="NChar(125)" />
    <Parameter Name="p_codeHasValue" Type="System.Boolean" DbType="Bit" />
    <Parameter Name="p_isStof" Type="System.Boolean" DbType="Bit" />
    <Parameter Name="p_isStofHasValue" Type="System.Boolean" DbType="Bit" />
    <Parameter Name="p_generiekGroepId" Type="System.Int32" DbType="Int" />
    <Parameter Name="p_generiekGroepIdHasValue" Type="System.Boolean" DbType="Bit" />
    <ElementType Name="CSLA_Generiek_SelectResult">
      <Column Name="generiekId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="naam" Type="System.String" DbType="NChar(125) NOT NULL" CanBeNull="false" />
      <Column Name="versieTimeStamp" Type="System.Data.Linq.Binary" DbType="rowversion NOT NULL" CanBeNull="false" />
      <Column Name="code" Type="System.String" DbType="NChar(125)" CanBeNull="true" />
      <Column Name="isStof" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="generiekGroepId" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.CSLA_Generiek_Update" Method="CSLA_Generiek_Update">
    <Parameter Name="p_versieTimeStamp" Type="System.Data.Linq.Binary" DbType="Timestamp" Direction="InOut" />
    <Parameter Name="p_generiekId" Type="System.Int32" DbType="Int" />
    <Parameter Name="p_naam" Type="System.String" DbType="NChar(125)" />
    <Parameter Name="p_code" Type="System.String" DbType="NChar(125)" />
    <Parameter Name="p_isStof" Type="System.Boolean" DbType="Bit" />
    <Parameter Name="p_generiekGroepId" Type="System.Int32" DbType="Int" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.CSLA_GeneriekGroep_Delete" Method="CSLA_GeneriekGroep_Delete">
    <Parameter Name="p_generiekGroepId" Type="System.Int32" DbType="Int" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.CSLA_GeneriekGroep_Insert" Method="CSLA_GeneriekGroep_Insert">
    <Parameter Name="p_versieTimeStamp" Type="System.Data.Linq.Binary" DbType="Timestamp" Direction="InOut" />
    <Parameter Name="p_naam" Type="System.String" DbType="NChar(125)" />
    <Parameter Name="p_hoofdGroep" Type="System.Int32" DbType="Int" />
    <Parameter Name="p_generiekGroepId" Type="System.Int32" DbType="Int" Direction="InOut" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.CSLA_GeneriekGroep_Select" Method="CSLA_GeneriekGroep_Select">
    <Parameter Name="p_generiekGroepId" Type="System.Int32" DbType="Int" />
    <Parameter Name="p_naam" Type="System.String" DbType="NChar(125)" />
    <Parameter Name="p_hoofdGroep" Type="System.Int32" DbType="Int" />
    <Parameter Name="p_hoofdGroepHasValue" Type="System.Boolean" DbType="Bit" />
    <ElementType Name="CSLA_GeneriekGroep_SelectResult">
      <Column Name="generiekGroepId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="naam" Type="System.String" DbType="NChar(125) NOT NULL" CanBeNull="false" />
      <Column Name="versieTimeStamp" Type="System.Data.Linq.Binary" DbType="rowversion NOT NULL" CanBeNull="false" />
      <Column Name="hoofdGroep" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.CSLA_GeneriekGroep_Update" Method="CSLA_GeneriekGroep_Update">
    <Parameter Name="p_versieTimeStamp" Type="System.Data.Linq.Binary" DbType="Timestamp" Direction="InOut" />
    <Parameter Name="p_generiekGroepId" Type="System.Int32" DbType="Int" />
    <Parameter Name="p_naam" Type="System.String" DbType="NChar(125)" />
    <Parameter Name="p_hoofdGroep" Type="System.Int32" DbType="Int" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.CSLA_Route_Delete" Method="CSLA_Route_Delete">
    <Parameter Name="p_routeId" Type="System.Int32" DbType="Int" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.CSLA_Route_Insert" Method="CSLA_Route_Insert">
    <Parameter Name="p_versieTimeStamp" Type="System.Data.Linq.Binary" DbType="Timestamp" Direction="InOut" />
    <Parameter Name="p_naam" Type="System.String" DbType="NChar(125)" />
    <Parameter Name="p_routeId" Type="System.Int32" DbType="Int" Direction="InOut" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.CSLA_Route_Select" Method="CSLA_Route_Select">
    <Parameter Name="p_routeId" Type="System.Int32" DbType="Int" />
    <Parameter Name="p_naam" Type="System.String" DbType="NChar(125)" />
    <ElementType Name="CSLA_Route_SelectResult">
      <Column Name="routeId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="naam" Type="System.String" DbType="NChar(125) NOT NULL" CanBeNull="false" />
      <Column Name="versieTimeStamp" Type="System.Data.Linq.Binary" DbType="rowversion NOT NULL" CanBeNull="false" />
    </ElementType>
  </Function>
  <Function Name="dbo.CSLA_Route_Update" Method="CSLA_Route_Update">
    <Parameter Name="p_versieTimeStamp" Type="System.Data.Linq.Binary" DbType="Timestamp" Direction="InOut" />
    <Parameter Name="p_routeId" Type="System.Int32" DbType="Int" />
    <Parameter Name="p_naam" Type="System.String" DbType="NChar(125)" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.CSLA_ToedienVorm_Delete" Method="CSLA_ToedienVorm_Delete">
    <Parameter Name="p_toedienVormId" Type="System.Int32" DbType="Int" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.CSLA_ToedienVorm_Insert" Method="CSLA_ToedienVorm_Insert">
    <Parameter Name="p_versieTimeStamp" Type="System.Data.Linq.Binary" DbType="Timestamp" Direction="InOut" />
    <Parameter Name="p_naam" Type="System.String" DbType="NChar(125)" />
    <Parameter Name="p_toedienVormId" Type="System.Int32" DbType="Int" Direction="InOut" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.CSLA_ToedienVorm_Select" Method="CSLA_ToedienVorm_Select">
    <Parameter Name="p_toedienVormId" Type="System.Int32" DbType="Int" />
    <Parameter Name="p_naam" Type="System.String" DbType="NChar(125)" />
    <ElementType Name="CSLA_ToedienVorm_SelectResult">
      <Column Name="toedienVormId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="naam" Type="System.String" DbType="NChar(125) NOT NULL" CanBeNull="false" />
      <Column Name="versieTimeStamp" Type="System.Data.Linq.Binary" DbType="rowversion NOT NULL" CanBeNull="false" />
    </ElementType>
  </Function>
  <Function Name="dbo.CSLA_ToedienVorm_Update" Method="CSLA_ToedienVorm_Update">
    <Parameter Name="p_versieTimeStamp" Type="System.Data.Linq.Binary" DbType="Timestamp" Direction="InOut" />
    <Parameter Name="p_toedienVormId" Type="System.Int32" DbType="Int" />
    <Parameter Name="p_naam" Type="System.String" DbType="NChar(125)" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.CSLA_ToedienVormRoute_Delete" Method="CSLA_ToedienVormRoute_Delete">
    <Parameter Name="p_toedienVormRouteId" Type="System.Int32" DbType="Int" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.CSLA_ToedienVormRoute_Insert" Method="CSLA_ToedienVormRoute_Insert">
    <Parameter Name="p_toedienVormId" Type="System.Int32" DbType="Int" />
    <Parameter Name="p_routeId" Type="System.Int32" DbType="Int" />
    <Parameter Name="p_toedienVormRouteId" Type="System.Int32" DbType="Int" Direction="InOut" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.CSLA_ToedienVormRoute_Select" Method="CSLA_ToedienVormRoute_Select">
    <Parameter Name="p_toedienVormRouteId" Type="System.Int32" DbType="Int" />
    <Parameter Name="p_toedienVormId" Type="System.Int32" DbType="Int" />
    <Parameter Name="p_routeId" Type="System.Int32" DbType="Int" />
    <ElementType Name="CSLA_ToedienVormRoute_SelectResult">
      <Column Name="toedienVormRouteId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="toedienVormId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="routeId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
    </ElementType>
  </Function>
  <Function Name="dbo.CSLA_ToedienVormRoute_Update" Method="CSLA_ToedienVormRoute_Update">
    <Parameter Name="p_toedienVormRouteId" Type="System.Int32" DbType="Int" />
    <Parameter Name="p_toedienVormId" Type="System.Int32" DbType="Int" />
    <Parameter Name="p_routeId" Type="System.Int32" DbType="Int" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.CSLA_ToedienVormVerpakking_Delete" Method="CSLA_ToedienVormVerpakking_Delete">
    <Parameter Name="p_toedienVormVerpakkingId" Type="System.Int32" DbType="Int" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.CSLA_ToedienVormVerpakking_Insert" Method="CSLA_ToedienVormVerpakking_Insert">
    <Parameter Name="p_toedienVormId" Type="System.Int32" DbType="Int" />
    <Parameter Name="p_verpakkingId" Type="System.Int32" DbType="Int" />
    <Parameter Name="p_toedienVormVerpakkingId" Type="System.Int32" DbType="Int" Direction="InOut" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.CSLA_ToedienVormVerpakking_Select" Method="CSLA_ToedienVormVerpakking_Select">
    <Parameter Name="p_toedienVormVerpakkingId" Type="System.Int32" DbType="Int" />
    <Parameter Name="p_toedienVormId" Type="System.Int32" DbType="Int" />
    <Parameter Name="p_verpakkingId" Type="System.Int32" DbType="Int" />
    <ElementType Name="CSLA_ToedienVormVerpakking_SelectResult">
      <Column Name="toedienVormVerpakkingId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="toedienVormId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="verpakkingId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
    </ElementType>
  </Function>
  <Function Name="dbo.CSLA_ToedienVormVerpakking_Update" Method="CSLA_ToedienVormVerpakking_Update">
    <Parameter Name="p_toedienVormVerpakkingId" Type="System.Int32" DbType="Int" />
    <Parameter Name="p_toedienVormId" Type="System.Int32" DbType="Int" />
    <Parameter Name="p_verpakkingId" Type="System.Int32" DbType="Int" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.CSLA_Verpakking_Delete" Method="CSLA_Verpakking_Delete">
    <Parameter Name="p_verpakkingId" Type="System.Int32" DbType="Int" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.CSLA_Verpakking_Insert" Method="CSLA_Verpakking_Insert">
    <Parameter Name="p_versieTimeStamp" Type="System.Data.Linq.Binary" DbType="Timestamp" Direction="InOut" />
    <Parameter Name="p_naam" Type="System.String" DbType="NChar(125)" />
    <Parameter Name="p_verpakkingId" Type="System.Int32" DbType="Int" Direction="InOut" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.CSLA_Verpakking_Select" Method="CSLA_Verpakking_Select">
    <Parameter Name="p_verpakkingId" Type="System.Int32" DbType="Int" />
    <Parameter Name="p_naam" Type="System.String" DbType="NChar(125)" />
    <ElementType Name="CSLA_Verpakking_SelectResult">
      <Column Name="verpakkingId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="naam" Type="System.String" DbType="NChar(125) NOT NULL" CanBeNull="false" />
      <Column Name="versieTimeStamp" Type="System.Data.Linq.Binary" DbType="rowversion NOT NULL" CanBeNull="false" />
    </ElementType>
  </Function>
  <Function Name="dbo.CSLA_Verpakking_Update" Method="CSLA_Verpakking_Update">
    <Parameter Name="p_versieTimeStamp" Type="System.Data.Linq.Binary" DbType="Timestamp" Direction="InOut" />
    <Parameter Name="p_verpakkingId" Type="System.Int32" DbType="Int" />
    <Parameter Name="p_naam" Type="System.String" DbType="NChar(125)" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.CSLA_Merk_Delete" Method="CSLA_Merk_Delete">
    <Parameter Name="p_merkId" Type="System.Int32" DbType="Int" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.CSLA_Merk_Insert" Method="CSLA_Merk_Insert">
    <Parameter Name="p_versieTimeStamp" Type="System.Data.Linq.Binary" DbType="Timestamp" Direction="InOut" />
    <Parameter Name="p_naam" Type="System.String" DbType="NChar(125)" />
    <Parameter Name="p_merkId" Type="System.Int32" DbType="Int" Direction="InOut" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.CSLA_Merk_Select" Method="CSLA_Merk_Select">
    <Parameter Name="p_merkId" Type="System.Int32" DbType="Int" />
    <Parameter Name="p_naam" Type="System.String" DbType="NChar(125)" />
    <ElementType Name="CSLA_Merk_SelectResult">
      <Column Name="merkId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="naam" Type="System.String" DbType="NChar(125) NOT NULL" CanBeNull="false" />
      <Column Name="versieTimeStamp" Type="System.Data.Linq.Binary" DbType="rowversion NOT NULL" CanBeNull="false" />
    </ElementType>
  </Function>
  <Function Name="dbo.CSLA_Merk_Update" Method="CSLA_Merk_Update">
    <Parameter Name="p_versieTimeStamp" Type="System.Data.Linq.Binary" DbType="Timestamp" Direction="InOut" />
    <Parameter Name="p_merkId" Type="System.Int32" DbType="Int" />
    <Parameter Name="p_naam" Type="System.String" DbType="NChar(125)" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.CSLA_DeleteArtikelGenerieksByAndartikelId" Method="CSLA_DeleteArtikelGenerieksByAndartikelId">
    <Parameter Name="artikelId" Type="System.Int32" DbType="Int" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.CSLA_DeleteArtikelGenerieksByAndeenheidId" Method="CSLA_DeleteArtikelGenerieksByAndeenheidId">
    <Parameter Name="eenheidId" Type="System.Int32" DbType="Int" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.CSLA_DeleteArtikelGenerieksByAndgeneriekId" Method="CSLA_DeleteArtikelGenerieksByAndgeneriekId">
    <Parameter Name="generiekId" Type="System.Int32" DbType="Int" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.CSLA_DeleteArtikelRoutesByAndartikelId" Method="CSLA_DeleteArtikelRoutesByAndartikelId">
    <Parameter Name="artikelId" Type="System.Int32" DbType="Int" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.CSLA_DeleteArtikelRoutesByAndrouteId" Method="CSLA_DeleteArtikelRoutesByAndrouteId">
    <Parameter Name="routeId" Type="System.Int32" DbType="Int" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.CSLA_DeleteToedienVormEenheidsByAndeenheidId" Method="CSLA_DeleteToedienVormEenheidsByAndeenheidId">
    <Parameter Name="eenheidId" Type="System.Int32" DbType="Int" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.CSLA_DeleteToedienVormEenheidsByAndtoedienVormId" Method="CSLA_DeleteToedienVormEenheidsByAndtoedienVormId">
    <Parameter Name="toedienVormId" Type="System.Int32" DbType="Int" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.CSLA_DeleteToedienVormRoutesByAndrouteId" Method="CSLA_DeleteToedienVormRoutesByAndrouteId">
    <Parameter Name="routeId" Type="System.Int32" DbType="Int" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.CSLA_DeleteToedienVormRoutesByAndtoedienVormId" Method="CSLA_DeleteToedienVormRoutesByAndtoedienVormId">
    <Parameter Name="toedienVormId" Type="System.Int32" DbType="Int" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.CSLA_DeleteToedienVormVerpakkingsByAndtoedienVormId" Method="CSLA_DeleteToedienVormVerpakkingsByAndtoedienVormId">
    <Parameter Name="toedienVormId" Type="System.Int32" DbType="Int" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.CSLA_DeleteToedienVormVerpakkingsByAndverpakkingId" Method="CSLA_DeleteToedienVormVerpakkingsByAndverpakkingId">
    <Parameter Name="verpakkingId" Type="System.Int32" DbType="Int" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.CSLA_ToedienVormEenheid_Delete" Method="CSLA_ToedienVormEenheid_Delete">
    <Parameter Name="p_toedienVormEenheidId" Type="System.Int32" DbType="Int" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.CSLA_ToedienVormEenheid_Insert" Method="CSLA_ToedienVormEenheid_Insert">
    <Parameter Name="p_toedienVormId" Type="System.Int32" DbType="Int" />
    <Parameter Name="p_eenheidId" Type="System.Int32" DbType="Int" />
    <Parameter Name="p_toedienVormEenheidId" Type="System.Int32" DbType="Int" Direction="InOut" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.CSLA_ToedienVormEenheid_Select" Method="CSLA_ToedienVormEenheid_Select">
    <Parameter Name="p_toedienVormEenheidId" Type="System.Int32" DbType="Int" />
    <Parameter Name="p_toedienVormId" Type="System.Int32" DbType="Int" />
    <Parameter Name="p_eenheidId" Type="System.Int32" DbType="Int" />
    <ElementType Name="CSLA_ToedienVormEenheid_SelectResult">
      <Column Name="toedienVormEenheidId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="toedienVormId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="eenheidId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
    </ElementType>
  </Function>
  <Function Name="dbo.CSLA_ToedienVormEenheid_Update" Method="CSLA_ToedienVormEenheid_Update">
    <Parameter Name="p_toedienVormEenheidId" Type="System.Int32" DbType="Int" />
    <Parameter Name="p_toedienVormId" Type="System.Int32" DbType="Int" />
    <Parameter Name="p_eenheidId" Type="System.Int32" DbType="Int" />
    <Return Type="System.Int32" />
  </Function>
</Database>